import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Badge from "@/components/ds/Badge";
import { createPageMetadata } from "@/lib/seo";

export const metadata=createPageMetadata({path:"/docs/einsguard-ai/install",title:"EINSGUARD AI 0.3.0 설치·설정 매뉴얼 | EINSTECH",description:"EINSGUARD AI 관리 서버에 고객사 내부 LLM을 연결하고 Windows Agent 1.2.4와 Linux·macOS Agent를 등록하는 방법입니다."});
const Code=({children})=><pre className="mt-4 overflow-x-auto rounded-xl border border-slate-300 bg-slate-100 p-5 font-mono text-xs font-semibold leading-6 text-slate-950 shadow-inner"><code>{children}</code></pre>;
const Title=({n,children})=><h2 className="font-display text-3xl font-black"><span className="mr-3 text-blue-700">{n}</span>{children}</h2>;

export default function InstallPage(){return <><Header/><main className="bg-slate-50 pt-16 text-slate-900"><section className="border-b border-slate-300 bg-white py-20"><div className="mx-auto max-w-4xl px-6"><Badge>0.3.0-TRIAL</Badge><h1 className="mt-6 font-display text-5xl font-black">설치·내부 LLM 설정 매뉴얼</h1><p className="mt-5 text-base leading-8 text-slate-600">관리 서버 설치부터 고객사 내부 LLM 선택, Windows·Linux·macOS Agent 등록과 문제 해결까지 설명합니다.</p></div></section><article className="mx-auto max-w-4xl space-y-16 px-6 py-16 text-sm leading-7">
<section><Title n="1">구성 및 요구사항</Title><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-slate-300 bg-white p-5"><b>관리 서버</b><p className="mt-2 text-slate-600">Linux x86_64/arm64, RAM 4GB 이상, 디스크 10GB 이상, Docker/Podman Compose, TCP 3100</p></div><div className="rounded-xl border border-slate-300 bg-white p-5"><b>Agent와 내부 LLM</b><p className="mt-2 text-slate-600">Windows 10·11 x64, Linux systemd, macOS 13 이상. 내부 LLM은 선택 사항이며 Ollama 또는 OpenAI 호환 API를 지원합니다.</p></div></div></section>
<section><Title n="2">파일 검증과 압축 해제</Title><Code>{`sha256sum -c einsguard-ai-0.3.0-trial-linux.tar.gz.sha256\ntar -xzf einsguard-ai-0.3.0-trial-linux.tar.gz\ncd einsguard-ai-0.3.0-trial`}</Code></section>
<section><Title n="3">관리 서버와 내부 LLM 설정</Title><Code>{`./ai-sentinel-dashboard/release/preflight.sh\n./ai-sentinel-dashboard/release/install.sh`}</Code><p className="mt-3 text-slate-600">설치 중 <b>사용 안 함</b>, <b>Ollama</b>, <b>OpenAI 호환 API</b> 중 하나를 선택합니다. Ollama는 주소와 모델명을, vLLM·LocalAI·LM Studio 등은 OpenAI 호환 주소·모델명·필요 시 API 키를 입력합니다. 관리 서버 호스트의 LLM은 기본값 <code>host.docker.internal</code>을 사용할 수 있습니다.</p><div className="mt-4 rounded-xl border border-emerald-400 bg-emerald-50 p-5"><b>설치 전 연결 시험</b><p className="mt-2">입력한 서버에서 모델을 찾지 못하면 설치가 중단됩니다. Windows와 Linux Agent에는 관리 서버 주소만 입력하며, 장비 전용 연결 키는 관리자가 등록 요청을 승인하면 자동 설정됩니다.</p></div></section>
<section><Title n="4">Windows Agent 1.2.4</Title><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6 text-slate-700"><li><b>1.</b> EINSGUARD-AI-Windows-Agent-1.2.4.exe를 실행하고 UAC를 승인합니다.</li><li><b>2.</b> 관리 서버 IP 또는 URL을 입력합니다.</li><li><b>3.</b> 대시보드 → AI 자산에서 신규 등록 요청을 승인합니다.</li><li><b>4.</b> 설치 후 클립보드·CLI DLP와 Claude·Codex 실행 정책이 적용됩니다.</li><li><b>5.</b> 초기 운영은 Monitor 모드로 검증한 뒤 관리자가 Enforce 모드로 전환합니다.</li></ol><h3 className="mt-7 text-xl font-black">상태 확인</h3><Code>{`powershell -ExecutionPolicy Bypass -File "C:\\ProgramData\\EINSTECH\\AI-Sentinel\\Test-EINSGUARD-Agent.ps1"`}</Code><p className="mt-3 text-slate-600">제거는 Windows 설정의 설치된 앱에서 <b>EINSGUARD AI Windows Agent</b>를 선택합니다. 정책 차단 시 PowerShell에는 EINSGUARD AI 안내 한 줄만 표시됩니다.</p></section>
<section><Title n="5">Linux Agent 1.2.1 · macOS Agent</Title><h3 className="mt-7 text-xl font-black">Linux: 서버 IP만 입력</h3><Code>{`sha256sum -c einsguard-ai-agent-1.2.1-linux.tar.gz.sha256\ntar -xzf einsguard-ai-agent-1.2.1-linux.tar.gz\ncd einsguard-ai-agent-1.2.1-linux\nsudo ./install.sh 서버IP\nsudo ./status.sh\n\n# 예: sudo ./install.sh 192.168.0.123`}</Code><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6 text-slate-700"><li><b>1.</b> 설치 프로그램이 관리 서버에 이 Linux 장비의 등록을 요청합니다.</li><li><b>2.</b> 관리자는 대시보드 → AI 자산 → Agent 등록 요청에서 장비를 확인하고 승인합니다.</li><li><b>3.</b> 설치 프로그램이 장비 전용 Agent 키를 자동 수령해 권한 600으로 저장하고 서비스를 시작합니다.</li><li><b>4.</b> 승인 대기는 최대 10분이며, 초과되면 같은 설치 명령을 다시 실행합니다.</li><li><b>5.</b> 재설치 시 변경된 서버 주소를 적용하도록 서비스가 자동 재시작되며 로컬 사용자 추가·삭제 상태도 보고합니다.</li></ol><h3 className="mt-7 text-xl font-black">macOS</h3><Code>{`cd ai-sentinel/agents/macos\nsudo ./install-system.sh http://서버IP:3100 AGENT_KEY\nsudo ./status.sh`}</Code><p className="mt-3 text-slate-600">Linux 사용자는 라이선스 키나 Agent 키를 입력하지 않습니다. 내부 영구 버전과 고객용 Trial 모두 같은 승인 등록 방식을 사용합니다. macOS도 추후 같은 자동 승인 방식으로 통합할 예정입니다.</p></section>
<section><Title n="6">내용 처리 범위와 성능</Title><p className="mt-4 text-slate-600">원문은 기본적으로 저장하지 않고 내부 LLM 판정 중에만 일시 사용합니다. Windows는 클립보드·CLI, Linux·macOS는 CLI를 검사합니다. 웹 채팅 입력창 전체 검사는 브라우저 확장·보안 프록시·서비스 공식 감사 연동이 별도로 필요합니다.</p><p className="mt-3 text-slate-600">LLM 판정은 사건 수집 응답 뒤 백그라운드로 실행됩니다. 기본 제한시간은 5초이며 연속 장애 시 회로 차단기가 작동해 Agent 지연을 방지합니다.</p></section>
<section><Title n="7">기존 설치 변경·백업·문제 해결</Title><Code>{`# 내부 LLM 변경\n./ai-sentinel-dashboard/release/configure-local-ai.sh\n\n# 백업과 업데이트\n./ai-sentinel-dashboard/release/backup.sh\n./ai-sentinel-dashboard/release/update.sh`}</Code><div className="mt-5 overflow-hidden rounded-xl border border-slate-300 bg-white"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">증상</th><th className="p-3">확인</th></tr></thead><tbody className="divide-y divide-slate-200"><tr><td className="p-3 font-bold">모델을 찾지 못함</td><td className="p-3">LLM 주소·모델명과 컨테이너에서의 접근 경로 확인</td></tr><tr><td className="p-3 font-bold">판정 지연</td><td className="p-3">대시보드의 ai_latency_ms와 5초 제한·회로 차단 상태 확인</td></tr><tr><td className="p-3 font-bold">Unauthorized agent</td><td className="p-3">대시보드에서 기존 등록 상태를 확인한 뒤 Agent를 다시 등록·승인</td></tr></tbody></table></div></section>
<div className="flex flex-col gap-3 sm:flex-row"><a href="/downloads/einsguard-ai" className="rounded-xl bg-slate-950 px-6 py-4 text-center font-black text-white">다운로드 센터</a><a href="/docs/einsguard-ai/admin" className="rounded-xl border border-slate-300 bg-white px-6 py-4 text-center font-black">관리자 운영 매뉴얼</a><a href="/contact?type=EINSGUARD%20AI" className="rounded-xl border border-slate-300 bg-white px-6 py-4 text-center font-black">기술지원 문의</a></div>
</article></main><Footer/></>}
