import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Badge from "@/components/ds/Badge";
import { createPageMetadata } from "@/lib/seo";

export const metadata=createPageMetadata({path:"/docs/einsguard-ai/install",title:"EINSGUARD AI 1.0 설치·사용 매뉴얼 | EINSTECH",description:"AI GUARD 관리 서버와 Windows·Linux·macOS Agent 설치, 상태 확인, 운영, 제거 및 문제 해결 방법입니다."});
const Code=({children})=><pre className="mt-4 overflow-x-auto rounded-xl border border-slate-300 bg-slate-100 p-5 font-mono text-xs font-semibold leading-6 text-slate-950 shadow-inner"><code className="text-slate-950">{children}</code></pre>;
const Title=({n,children})=><h2 className="font-display text-3xl font-black"><span className="mr-3 text-blue-700">{n}</span>{children}</h2>;

export default function InstallPage(){return <><Header/><main className="bg-slate-50 pt-16 text-slate-900"><section className="border-b border-slate-300 bg-white py-20"><div className="mx-auto max-w-4xl px-6"><Badge>VERSION 1.0</Badge><h1 className="mt-6 font-display text-5xl font-black">설치·사용·문제해결 매뉴얼</h1><p className="mt-5 text-base leading-8 text-slate-600">관리 서버 설치부터 Windows·Linux·macOS Agent 연결, 대시보드 확인, 제거와 로그 수집까지 순서대로 설명합니다.</p></div></section><article className="mx-auto max-w-4xl space-y-16 px-6 py-16 text-sm leading-7">
<section><Title n="1">구성 및 요구사항</Title><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-xl border border-slate-300 bg-white p-5"><b>관리 서버</b><p className="mt-2 text-slate-600">Linux x86_64/arm64, RAM 4GB 이상, 디스크 10GB 이상, Docker Compose 또는 Podman Compose, TCP 3100</p></div><div className="rounded-xl border border-slate-300 bg-white p-5"><b>Agent</b><p className="mt-2 text-slate-600">Windows 10·11 x64, Linux systemd 또는 macOS 13 이상, Python 3, 관리자 권한, 관리 서버 TCP 3100 통신</p></div></div><div className="mt-4 rounded-xl border-2 border-amber-400 bg-amber-50 p-5"><b>15일 무료 라이선스</b><p className="mt-2 text-slate-700">최초 서버 설치일부터 15일간 무료입니다. 만료 후 서버가 Agent 정책 조회·로그 수집·탐지·차단 요청을 거부하므로 자동으로 동작하지 않습니다. 기존 로그와 설치 파일은 유지되며, 구독 키 인증 후 다시 동작합니다.</p></div></section>
<section><Title n="2">파일 무결성 확인</Title><Code>{`sha256sum -c 다운로드한파일.tar.gz.sha256\n# macOS\nshasum -a 256 다운로드한파일.tar.gz`}</Code><p className="mt-3 text-slate-600">결과가 홈페이지의 SHA-256 값과 다르면 설치하지 말고 다시 다운로드하십시오.</p></section>
<section><Title n="3">관리 서버 설치</Title><Code>{`tar -xzf einsguard-ai-server-1.0.0-linux.tar.gz\ncd einsguard-ai-server-1.0.0\n./ai-sentinel-dashboard/release/preflight.sh\n./ai-sentinel-dashboard/release/install.sh`}</Code><p className="mt-3 text-slate-600">12자 이상의 초기 관리자 비밀번호를 입력합니다. 설치 완료 후 <b>http://서버IP:3100</b>에 접속하십시오. 서버 설정의 <code>INIT_AGENT_KEY</code>는 Agent 설치에 필요하며 외부에 공개하면 안 됩니다.</p></section>
<section><Title n="4">Windows Agent 1.0.2 설치</Title><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6 text-slate-700"><li><b>1.</b> EINSGUARD-AI-Windows-Agent-1.0.exe를 내려받아 더블클릭합니다.</li><li><b>2.</b> UAC 관리자 권한을 승인하고 관리 서버 IP 또는 http://서버IP:3100을 입력합니다.</li><li><b>3.</b> 대시보드 → AI 자산에서 신규 등록 요청을 승인합니다. 기존 Agent가 설치된 PC는 승인 없이 재등록됩니다.</li><li><b>4.</b> 설치 프로그램이 Agent를 갱신하고, 다음 로그인부터 PowerShell 창 없이 백그라운드에서 실행합니다.</li></ol><div className="mt-4 rounded-xl border border-emerald-400 bg-emerald-50 p-5"><b>정상 메시지</b><p className="mt-2">설치가 완료됐습니다. 새 PowerShell/명령 프롬프트에서 AI를 실행하세요.</p><p className="mt-2">진단 결과는 EINSGUARD AI Agent status: HEALTHY가 정상입니다.</p></div><h3 className="mt-7 text-xl font-black">상태 확인</h3><Code>{`powershell -ExecutionPolicy Bypass -File "C:\\ProgramData\\EINSTECH\\AI-Sentinel\\Test-EINSGUARD-Agent.ps1"`}</Code><p className="mt-3">설치 로그: C:\ProgramData\EINSTECH\AI-Sentinel\logs\install.log</p><h3 className="mt-7 text-xl font-black">Windows 제거</h3><ol className="mt-4 space-y-2 rounded-xl border border-slate-300 bg-white p-6"><li>1. EINSGUARD-AI-Cleanup-1.0.exe를 다운로드합니다.</li><li>2. 더블클릭하고 UAC를 승인합니다.</li><li>3. 제거 로그: C:\ProgramData\EINSTECH\AI-GUARD-Logs\uninstall-날짜.log</li></ol></section>
<section><Title n="5">Linux Agent 설치</Title><Code>{`tar -xzf einsguard-ai-agent-1.0.0-linux.tar.gz\ncd einsguard-ai-agent-1.0.0-linux\nsudo ./install.sh http://서버IP:3100 AGENT_KEY\nsudo ./status.sh`}</Code><p className="mt-3 text-slate-600">정상 메시지는 <b>EINSGUARD AI Linux Agent 1.0 installed successfully</b>와 <b>Service: RUNNING</b>입니다. 로그는 <code>/var/log/einsguard-ai/</code>에 있습니다.</p></section>
<section><Title n="6">macOS Agent 설치</Title><Code>{`tar -xzf einsguard-ai-agent-1.0.0-macos.tar.gz\ncd einsguard-ai-agent-1.0.0-macos\nsudo ./install.sh http://서버IP:3100 AGENT_KEY\nsudo ./status.sh`}</Code><p className="mt-3 text-slate-600">정상 메시지는 <b>EINSGUARD AI macOS Agent 1.0 installed successfully</b>와 <b>Service: RUNNING</b>입니다. 로그는 <code>/Library/Logs/einsguard-ai*.log</code>에 있습니다.</p></section>
<section><Title n="7">대시보드 사용 순서</Title><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6 text-slate-700"><li><b>1.</b> AI 자산에서 Client가 온라인인지 확인합니다.</li><li><b>2.</b> Client 검색에서 PC명·사용자·운영체제·AI 서비스를 찾습니다.</li><li><b>3.</b> 업무용 AI는 해당 Client의 AI 버튼을 눌러 승인합니다.</li><li><b>4.</b> 미승인 AI는 에이전트 제어 → 차단 관리에서 정책을 적용합니다.</li><li><b>5.</b> Shadow AI 이벤트를 펼쳐 발생 위치·현재 조치·해결 방법을 확인합니다.</li><li><b>6.</b> 조치가 끝난 사건만 ‘확인 후 해결 처리’합니다.</li></ol></section>
<section><Title n="8">Linux·macOS 및 서버 제거</Title><Code>{`# Linux 또는 macOS Agent 압축 해제 폴더에서\nsudo ./uninstall.sh\n\n# 서버: 데이터 보존 기본 제거\n./ai-sentinel-dashboard/release/uninstall.sh`}</Code><p className="mt-3 text-slate-600">Agent 제거 로그는 Linux <code>/var/log/einsguard-ai/</code>, macOS <code>/Library/Logs/</code>에 남습니다. 서버 데이터 완전 삭제는 백업과 별도 승인 없이 수행하지 마십시오.</p></section>
<section><Title n="9">문제 해결</Title><div className="mt-5 overflow-hidden rounded-xl border border-slate-300 bg-white"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">증상</th><th className="p-3">확인 및 해결</th></tr></thead><tbody className="divide-y divide-slate-200"><tr><td className="p-3 font-bold">Client가 안 보임</td><td className="p-3">status.sh 실행 → 서버 URL 확인 → TCP 3100 방화벽 확인 → Agent 오류 로그 확인</td></tr><tr><td className="p-3 font-bold">Service: STOPPED</td><td className="p-3">Linux는 systemctl status einsguard-ai, macOS는 launchctl print system/com.einstech.einsguard-ai 확인</td></tr><tr><td className="p-3 font-bold">Unauthorized agent</td><td className="p-3">Agent 키가 해당 고객 서버의 키인지 확인하고 재설치</td></tr><tr><td className="p-3 font-bold">승인되지 않은 CLI 차단</td><td className="p-3">이벤트를 펼쳐 PC·사용자·AI 확인 → 업무용이면 AI 자산에서 승인 → 아니면 차단 유지</td></tr><tr><td className="p-3 font-bold">한글이 ?로 표시</td><td className="p-3">서버 1.0은 이벤트 코드로 문구를 복원합니다. Agent 오류 로그를 지원 담당자에게 전달하십시오.</td></tr></tbody></table></div></section>
<div className="flex flex-col gap-3 sm:flex-row"><a href="/downloads/einsguard-ai" className="rounded-xl bg-slate-950 px-6 py-4 text-center font-black text-white">다운로드 센터</a><a href="/contact?type=EINSGUARD%20AI&subject=EINSGUARD%20AI%201.0%20설치%20문의" className="rounded-xl border border-slate-300 bg-white px-6 py-4 text-center font-black">기술지원 문의</a></div>
</article></main><Footer/></>}
