export const omadaApSpecs = {
  "EAP650": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap650/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 기가비트 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE• DC 12V (전원 어댑터 포함)(EU 버전: DC 12 V / 1.0 A. US 버전: DC 12 V / 1.5 A)• 48 V 패시브 PoE"],
        ["전력 소모", "• EU: 13.7 W• US: 15.5 W"],
        ["무게", "• 본체: 0.38 kg (0.838 lbs)• 마운팅 브라켓: 0.054 kg (0.119 lbs)• 배송 유닛 0.85 kg (1.87 lbs)"],
        ["크기 ( 가로 x 세로 x 높이 )", "• 본체: 160 × 160 × 33.6 mm (6.3 × 6.3 × 1.3 in)• 배송 유닛: 245 × 228 × 65 mm (9.7 × 9.0 × 2.6 in)"],
        ["안테나", "내장형 듀얼 밴드 안테나• 2.4 GHz: 2× 4 dBi• 5 GHz: 2× 5 dBi"],
        ["블루투스", "V5.2"],
        ["마운트", "• 천장/벽/정션 박스/ T바 설치  (키트 포함)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "Local/Remote Syslog"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "HTTP/HTTPS"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "지원. Omada 컨트롤러가 필요합니다."],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)*"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz 및 5 GHz"],
        ["신호 속도", "• 5 GHz: 최대 2402 Mbps• 2.4 GHz: 최대 574 Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 더 긴 OFDM 심볼• OFDMA• 다중 SSID (최대 16개의 SSID, 대역당 8개)• 무선 주파수 활성화/비활성화• 자동 채널 할당• 전송 전력 제어 (dBm 단위로 전송 전력 조절)• QoS (WMM)• MU-MIMO• HE160 (160 MHz 대역폭)‡• 심리스 로밍 (802.11k/v/r)△• Omada 메시△• 밴드 스티어링• 로드 밸런싱• Airtime Fairness• 빔포밍• 속도 제한• 재부팅 일정• 무선 일정 예약• SSID/AP/클라이언트 기반 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID-VLAN 매핑• 비인가 AP 탐지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE:7-20 dBm(2.4 GHz, EIRP)6-22 dBm5 GHz, U-NII-1, U-NII-2A, EIRP)6-27 dBm(5 GHz, U-NII-2C, EIRP)• FCC:4-26 dBm (2.4 GHz)4-24 dBm (5 GHz, U-NII-1)4-25 dBm (5 GHz, U-NII-2A, U-NII-2C, U-NII-3)"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• EAP650• 전원 어댑터• 마운팅 키트• 설치 가이드"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows 11, Linux"],
        ["사용 환경", "• 작동 온도: 0℃ ~ 40℃ (32℉ ~ 104℉)• 보관 온도: - 40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90 % RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP650-Outdoor": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-outdoor/eap650-outdoor/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 기가비트 이더넷(RJ45) 포트 (802.3at PoE 및 패시브 PoE 지원)"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE• 48 V 패시브 PoE (PoE 어댑터 제공 - 건조한 실내 환경 전용)"],
        ["전력 소모", "14.7 W (802.3at PoE 또는 패시브 PoE)"],
        ["크기 ( 가로 x 세로 x 높이 )", "106.5 × 57 × 281 mm (4.2 × 2.2 × 11.1 in)(안테나 및 마운팅 키트 제외)"],
        ["안테나", "• 2.4 GHz: 2× 4 dBi• 5 GHz: 2× 5 dBi"],
        ["방수방진 케이스", "IP68"],
        ["마운트", "기둥/벽면 설치 (키트 제공)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "지원"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
      ] },
      { title: "무선 기능", rows: [
        ["동시 접속 클라이언트", "250+6"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz, 5 GHz"],
        ["신호 속도", "• 802.11ax: 8 Mbps ~ 2402 Mbps (MCS0-MCS11, NSS = 1 to 2 HE20/40/80/160)• 802.11ac: 6.5 Mbps ~ 1083.3 Mbps (MCS0-MCS9, NSS = 1 to2 VHT20/40/80)• 802.11n: 6.5 Mbps ~ 300 Mbps (MCS0-MCS15, HT20/40)• 802.11g: 6, 9, 12, 18, 24, 36, 48, 54 Mbps• 802.11b: 1, 2, 5.5, 11 Mbps• 802.11a: 6, 9, 12, 18, 24, 36, 48, 54 Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 길어진 OFDM 심볼• OFDMA• 멀티 SSID (최대 16개 SSID, 대역당 8개)• 무선 주파수 활성화/비활성화• 자동 채널 할당• 전송 전력 제어 (dBm 단위로 전송 전력 조정)• QoS (WMM)• MU-MIMO• Omada 메시3• 심리스 로밍(802.11k/v/r)3• 밴드 스티어링• 로드 밸런싱• Airtime Fairness• 빔포밍• 속도 제한• 재부팅 일정• 무선 일정 예약• SSID/AP/클라이언트 기반 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증3• 액세스 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID to VLAN 매핑• 비인가 AP 감지• 802.1X 지원• WEP, WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE: < 20 dBm (2.4 GHz, EIRP), < 30 dBm (5 GHz, EIRP)• FCC: < 25 dBm (2.4 GHz), < 25 dBm (5 GHz)"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• 액세스 포인트 EAP650-Outdoor• 패시브 PoE 어댑터• 전원선• 마운팅 키트• 설치 가이드• 방수 키트"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows11, Linux"],
        ["사용 환경", "• 작동 온도: -30℃ ~ 70℃ (-22℉ ~ 158℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "EAP653": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap653/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 기가비트 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE• DC 12 V (전원 어댑터 미제공, 별도 구매 필요)(DC 12 V / 1.5 A)*48 V 패시브 PoE 지원 (인젝터 미제공)"],
        ["전력 소모", "14.7 W"],
        ["크기 ( 가로 x 세로 x 높이 )", "160 × 160 × 33.6 mm (6.3 × 6.3 × 1.3 in)"],
        ["안테나", "내장형 듀얼 밴드 안테나• 2.4 GHz: 2× 4 dBi• 5 GHz: 2× 5 dBi"],
        ["블루투스", "V5.2"],
        ["마운트", "• 천장/벽면/정션 박스/T바 설치 (키트 제공)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "로컬/원격 Syslog"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "HTTP/HTTPS"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "지원. Omada 컨트롤러가 필요합니다."],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)*"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz, 5 GHz"],
        ["신호 속도", "• 5 GHz: 최대 2402 Mbps• 2.4 GHz: 최대 574 Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 더 긴 OFDM 심볼• OFDMA• 멀티 SSID (최대 16개의 SSID, 대역당 8개)• 무선 주파수 활성화/비활성화• 자동 채널 할당• 전송 전력 제어 (dBm 단위로 전송 전력 조정)• QoS (WMM)• MU-MIMO• HE160 (160 MHz 대역폭)‡• 심리스 로밍§• Omada 메시§• 밴드 스티어링• 로드 밸런싱• Airtime Fairness• 빔포밍• 속도 제한• 재부팅 일정• 무선 일정• SSID/AP/클라이언트 기반 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증§• 액세스 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID - VLAN 매핑• 비인가 AP 감지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE:7-20 dBm (2.4 GHz, EIRP)7-23 dBm (5 GHz, U-NII-1, U-NII-2A, EIRP)7-30 dBm (5 GHz, U-NII-2C, EIRP)• FCC:4-25 dBm (2.4 GHz)4-25 dBm (5 GHz, U-NII-1, U-NII-2A, U-NII-2C, U-NII-3)"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• EAP653• 마운팅 키트• 설치 가이드"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows 11, Linux"],
        ["사용 환경", "• 작동 온도: 0℃ ~ 40℃ (32℉ ~ 104℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP660 HD": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap660-hd/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1개의 2.5Gbps 이더넷 포트 (IEEE802.3at PoE 지원)"],
        ["버튼", "리셋"],
        ["전원 공급", "• 802.3at PoE• 12V DC"],
        ["전력 소모", "• EU: 18.5W• US: 21.5W"],
        ["크기 ( 가로 x 세로 x 높이 )", "9.6 × 9.6 × 2.5 (243 × 243 × 64 mm)"],
        ["안테나", "내부 Omni 안테나• 2.4 GHz: 4× 4 dBi• 5 GHz: 4× 5 dBi"],
        ["마운트", "천장 /벽 마운트 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["동시 접속 클라이언트", "1,000+***"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4-2.5GHz，5.15~5.25GHz, 5.725~5.85GHz"],
        ["신호 속도", "• 5GHz: 최대 2402Mbps• 2.4GHz: 최대 1148Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 긴 OFDM 심볼• OFDMA• 다중 SSID (최대 16개 SSID, 각 밴드 당 8개)• 무선 기능 활성화 / 비활성화• 자동 채널 할당• 전송 강도 제어 (dBm 단위로 전송 강도 조절)• QoS(WMM)• MU-MIMO• 끊김없는 로밍• Omada Mesh△• 밴드 스티어링• 로드 밸런싱• 에어타임 페어니스• 빔 포밍• 속도 제한• 재부팅 스케쥴• 무선 스케쥴• SSID/AP/클라이언트 기반의 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증△• 접근 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID 와 VLAN 매핑• 비인가 AP 탐지• 802.1X 지원• WEP, WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE:<20 dBm (2.4GHz, EIRP)<23 dBm (5GHz, EIRP)• FCC:<26 dBm (2.4GHz)<26 dBm (5GHz)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러 (OC300)• Omada 하드웨어 컨트롤러 (OC200)• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원 (OC300, OC200, Omada 클라우드 기반 컨트롤러 혹은 Omada 소프트웨어 컨트롤러를 통해)"],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "로컬/리모트 시스템로그"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "HTTP/HTTPS"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "가능. 이 기능을 사용하려면 Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• EAP660 HD• 전원 어댑터• 천장/벽 마운트 키트• 설치 가이드"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Linux"],
        ["사용 환경", "• 작동 온도: -20~50 ℃ (-4~122 ℉)• 보관 온도: -40~70 ℃ (-40~158 ℉)• 작동 습도: 10~95% 상대습도 (비응축)• 보관 습도: 5~95% 상대습도 (비응축)"],
      ] },
    ],
  },
  "EAP670": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap670/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5 기가비트 RJ45 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE• DC 12 V/2 A (전원 어댑터 포함)"],
        ["전력 소모", "• EU: 20.8 W• US: 22.3 W"],
        ["무게", "• 본체: 0.68 kg (1.5 lbs)• 마운팅 브라켓: 0.05 kg (0.11 lbs)• 배송 유닛 1.16 kg (2.56 lbs)"],
        ["크기 ( 가로 x 세로 x 높이 )", "220 × 220 × 32.5 mm (8.7 × 8.7 × 1.3 in)"],
        ["안테나", "내장형 무지향성 안테나• 2.4 GHz: 2× 4 dBi• 5 GHz: 4× 5.5 dBi"],
        ["블루투스", "V5.2"],
        ["마운트", "천장/벽/정션 박스 설치 (키트 포함)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "Local/Remote Syslog"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "HTTP/HTTPS"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "지원. Omada 컨트롤러가 필요합니다."],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)*"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz 및 5 GHz"],
        ["신호 속도", "• 5 GHz: 최대 4804 Mbps• 2.4 GHz: 최대 574 Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 더 긴 OFDM 심볼• OFDMA• 다중 SSID (최대 16개의 SSID, 대역당 8개)• 무선 주파수 활성화/비활성화• 자동 채널 할당• 전송 전력 제어 (dBm 단위로 전송 전력 조절)• QoS (WMM)• MU-MIMO (5 G: 4x4 DL/UL MU-MIMO)• HE160 (160 MHz 대역폭)‡• 심리스 로밍 (802.11k/v/r)△• Omada 메시△• 밴드 스티어링• 로드 밸런싱• Airtime Fairness• 빔포밍• 속도 제한• 재부팅 일정• 무선 일정 예약• SSID/AP/클라이언트 기반 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID-VLAN 매핑• 비인가 AP 탐지• 802.1X 지원• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE:7-20 dBm (2.4 GHz, EIRP)9-23 dBm (5 GHz, U-NII-1 및 U-NII-2A, EIRP)9-30 dBm (5 GHz, U-NII-2C, EIRP)• FCC:4-25 dBm (2.4 GHz)7-28 dBm (5 GHz, U-NII-1 & U-NII-2A & U-NII2C & U-NII-3)"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• EAP670• 전원 어댑터• 천장/벽면/정션 박스 마운팅 키트• 설치 가이드"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows11, Linux"],
        ["사용 환경", "• 작동 온도: 0℃ ~ 40℃ (32℉ ~ 104℉)• 보관 온도: - 40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90 % RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP673": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap673/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5 기가비트 RJ45 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE• DC 12 V/2 A (전원 어댑터 미포함)"],
        ["전력 소모", "• EU: 20.8 W• US: 22.3 W"],
        ["무게", "• 본체: 0.68 kg (1.5 lbs)• 마운팅 브라켓: 0.05 kg (0.11 lbs)• 배송 유닛 1.16 kg (2.56 lbs)"],
        ["크기 ( 가로 x 세로 x 높이 )", "220 × 220 × 32.5 mm (8.7 × 8.7 × 1.3 in)"],
        ["안테나", "내장형 무지향성 안테나• 2.4 GHz: 2× 4 dBi• 5 GHz: 4× 5.5 dBi"],
        ["블루투스", "V5.2"],
        ["마운트", "천장/벽/정션 박스 설치 (키트 포함)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "Local/Remote Syslog"],
        ["SSH", "지원"],
        ["웹기반 관리기능", "HTTP/HTTPS"],
        ["L3 관리", "지원"],
        ["멀티 사이트 관리", "지원"],
        ["VLAN 관리", "지원"],
        ["제로 터치 프로비저닝", "지원. Omada 컨트롤러가 필요합니다."],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)*"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz 및 5 GHz"],
        ["신호 속도", "• 5 GHz: 최대 4804 Mbps• 2.4 GHz: 최대 574 Mbps"],
        ["무선 기능", "• 1024-QAM• 4배 더 긴 OFDM 심볼• OFDMA• 다중 SSID (최대 16개의 SSID, 대역당 8개)• 무선 주파수 활성화/비활성화• 자동 채널 할당• 전송 전력 제어 (dBm 단위로 전송 전력 조절)• QoS (WMM)• MU-MIMO (5 G: 4x4 DL/UL MU-MIMO)• HE160 (160 MHz 대역폭)‡• 심리스 로밍 (802.11k/v/r)△• Omada 메시△• 밴드 스티어링• 로드 밸런싱• Airtime Fairness• 빔포밍• 속도 제한• 재부팅 일정• 무선 일정 예약• SSID/AP/클라이언트 기반 무선 통계"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 무선 MAC 주소 필터링• 클라이언트 간 무선 격리• SSID-VLAN 매핑• 비인가 AP 탐지• 802.1X 지원• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "• CE:7-20 dBm (2.4 GHz, EIRP)9-23 dBm (5 GHz, U-NII-1 및 U-NII-2A, EIRP)9-30 dBm (5 GHz, U-NII-2C, EIRP)• FCC:4-25 dBm (2.4 GHz)7-28 dBm (5 GHz, U-NII-1 & U-NII-2A & U-NII2C & U-NII-3)"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• EAP673• 천장/벽면/정션 박스 마운팅 키트• 설치 가이드"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows11, Linux"],
        ["사용 환경", "• 작동 온도: 0℃ ~ 40℃ (32℉ ~ 104℉)• 보관 온도: - 40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90 % RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP720": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap720/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5G 이더넷 포트"],
        ["버튼", "Reset 버튼"],
        ["전원 공급", "802.3at PoE 또는 DC 12 V/1.5 A (전원 어댑터 포함)"],
        ["전력 소모", "• 16.8 W (PoE)• 13.0 W (DC)"],
        ["크기 ( 가로 x 세로 x 높이 )", "160 × 160 × 36.7 mm (6.3 × 6.3 × 1.4 in)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 2× 5.0 dBi"],
        ["마운트", "천장/벽/정션 박스 마운팅(키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140 ㎡(1500 ft²)***"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "2.4 GHz 및 5 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) + 2882 Mbps (5 GHz)"],
        ["무선 기능", "• MLO‡• 4K-QAM‡• 심리스 로밍• EHT160‡• 메시△• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID:16(대역당 8개)• 무선 일정 예약• 재부팅 일정 예약• QoS(WMM)• 속도 제한• 고정 IP/동적 IP• RADIUS 계정• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 최대 MAC 필터 개수: 4,000• 클라이언트 간 무선 격리• VLAN• 비인가 AP 감지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "< 20 dBm (2.4 GHz, EIRP)< 23 dBm (5 GHz, band 1&band 2, EIRP)< 28 dBm (5 GHz, band 3, EIRP)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada Central (클라우드 기반)• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원.Omada 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["웹기반 관리기능", "지원"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• Omada Wi-Fi 7 천장형 액세스 포인트 EAP720• 설치 가이드• 천장/벽/정션 박스 마운팅 키트• 전원 어댑터"],
        ["사용 환경", "• 작동 온도: 0 °C ~ 40 °C (32 °F ~ 104 °F)• 보관 온도: -40 °C ~ 70 °C (-40 °F ~ 158 °F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP723": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap723/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5G 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "802.3at PoE 또는 DC 12 V/1.5 A"],
        ["전력 소모", "• 16.8 W (PoE)• 13.0 W (DC)"],
        ["크기 ( 가로 x 세로 x 높이 )", "160 × 160 × 36.7 mm (6.3 × 6.3 × 1.4 in)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 2× 5.0 dBi"],
        ["마운트", "천장 설치/벽면 설치/정션 박스 설치 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)***"],
        ["동시 접속 클라이언트", "250+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "2.4 GHz, 5 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) + 2882 Mbps (5 GHz)"],
        ["무선 기능", "• MLO‡• 4K-QAM‡• 심리스 로밍• EHT160‡• 메시△• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID:16개(대역당 8개)• 무선 일정 예약• 재부팅 일정• QoS (WMM)• 속도 제한• 정적 IP/동적 IP• RADIUS 어카운팅• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 최대 MAC 필터 개수: 4,000개• 클라이언트 간 무선 격리• VLAN• 비인가 AP 탐지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "< 20 dBm (2.4 GHz, EIRP)< 23 dBm (5 GHz, band 1&band 2, EIRP)< 28 dBm (5 GHz, band 3, EIRP)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada Central (클라우드 기반)• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원, Omada 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["웹기반 관리기능", "지원"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• Omada Wi-Fi 7 천장형 액세스 포인트 EAP723• 설치 가이드• 천장/벽면/정션 박스 마운팅 키트"],
        ["사용 환경", "• 작동 온도: 0°C ~ 40°C (32°F ~ 104°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP770": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap770/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5G 이더넷 포트"],
        ["버튼", "Reset 버튼"],
        ["전원 공급", "802.3at PoE 또는 12 V/2.5 A DC"],
        ["전력 소모", "• 24.05 W (PoE)• 20.92 W (DC)"],
        ["크기 ( 가로 x 세로 x 높이 )", "220 × 220 × 32.5 mm (8.7 × 8.7 × 1.3 in)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 2× 5.0 dBi • 6 GHz: 2× 5.0 dBi"],
        ["블루투스", "1× 4.0 dBi, 블루투스 5.2*펌웨어 업데이트가 필요할 수 있습니다."],
        ["마운트", "천장/벽/정션 박스 마운팅 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140 ㎡ (1500 ft²)§"],
        ["동시 접속 클라이언트", "380+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "6 GHz, 5 GHz, 2.4 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) + 2882 Mbps (5 GHz) + 5765 Mbps (6 GHz)†"],
        ["무선 기능", "• MLO‡• 4K-QAM‡• MU-MIMO‡• 320 MHz 대역폭‡• 메시△• 심리스 로밍 (802.11k/v/r)△• BBS 컬러‡• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID:24 (대역당 8개)• 무선 일정 예약• 재부팅 일정 예약• QoS(WMM)• 속도 제한• 고정 IP/동적 IP• RADIUS Accounting• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• 최대 MAC 필터 개수: 4,000개• 클라이언트 간 무선 격리• VLAN• 비인가 AP 감지•WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "< 20 dBm (2.4 GHz, EIRP)< 23 dBm (5 GHz, band 1&band 2, EIRP)< 28 dBm (5 GHz, band 3, EIRP)< 23dBm (6 GHz, EIRP)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["웹기반 관리기능", "지원"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• Omada 천장형 액세스 포인트 EAP770• 설치 가이드• 전원 어댑터• 천장/벽/정션 박스 마운팅 키트"],
        ["사용 환경", "• 작동 온도: 0°C ~ 40°C (32°F ~ 104°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도 5%-90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP772": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap772/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5G 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "802.3at PoE 또는 DC 12 V/2.5 A"],
        ["전력 소모", "• 25.4 W (PoE)• 21.8 W (DC)"],
        ["크기 ( 가로 x 세로 x 높이 )", "220 × 220 × 32.5 mm (8.7 × 8.7 × 1.3 in)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 2× 5.0 dBi• 6 GHz: 2× 5.0 dBi"],
        ["블루투스", "1 × 4.0 dBi, Bluetooth 5.2*펌웨어 업데이트가 필요할 수 있습니다."],
        ["마운트", "천장 설치/벽면 설치/정션 박스 설치 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡ (1500 ft²)§"],
        ["동시 접속 클라이언트", "380+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "6 GHz, 5 GHz, 2.4 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) + 4324 Mbps (5 GHz) + 5765 Mbps (6 GHz)†"],
        ["무선 기능", "• MLO‡• 4K-QAM‡• MU-MIMO‡• 320 MHz 대역폭‡• 메시△• 심리스 로밍 (802.11k/v/r)△• BSS 컬러‡• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID: 24개(대역당 8개)• 무선 일정 예약• 재부팅 일정• QoS (WMM)• 속도 제한• 정적 IP/동적 IP• RADIUS 어카운팅• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 컨트롤• 최대 MAC 필터 수: 4,000• 클라이언트 간 무선 격리• VLAN• 비인가 AP 탐지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "< 25 dBm （2.4 GHz）< 25 dBm （5 GHz）< 23 dBm （6 GHz）"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원, Omada 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["웹기반 관리기능", "지원"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• Omada 천장형 액세스 포인트 EAP772• 설치 가이드• 천장/벽면/정션 박스 마운팅 키트"],
        ["사용 환경", "• 작동 온도: 0°C ~ 40°C (32°F ~ 104°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP772-Outdoor": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-outdoor/eap772-outdoor/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 2.5G Ethernet (RJ-45) Port (Support 802.3at PoE)"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3at PoE"],
        ["전력 소모", "21.5W (for PoE)"],
        ["크기 ( 가로 x 세로 x 높이 )", "9.1× 8.2 × 2.8 in (230 × 207.5 × 69.7 mm)"],
        ["안테나", "• 2.4 GHz: 2× 4 dBi• 5 GHz: 2× 6 dBi• 6 GHz: 2× 6 dBi"],
        ["GNSS", "L1 (1575.42 MHz) receiver, supporting GPS, Galileo, GLONASS, and BeiDou signalsReceive sensitivity: -164dBm (tracking)GPS antennas: Integrated 3dBi omnidirectional antennas"],
        ["블루투스", "BLE 5.2"],
        ["방수방진 케이스", "IP68"],
        ["마운트", "Pole/Wall Mounting (Kits included)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "Yes"],
        ["중앙 집중식 관리", "• Omada Cloud-Based Controller• Omada Hardware Controller• Omada Software Controller"],
        ["클라우스 액세스", "Yes. Require the use of an Omada controller."],
        ["이메일 경보", "Yes"],
        ["관리 MAC 액세스 컨트롤", "Yes"],
        ["SNMP", "v1, v2c"],
        ["시스템 로깅\t로컬/리모트 시스로그", "Yes"],
        ["SSH", "Yes"],
        ["웹기반 관리기능", "Yes"],
        ["L3 관리", "Yes"],
        ["멀티 사이트 관리", "Yes"],
        ["VLAN 관리", "Yes"],
        ["제로 터치 프로비저닝", "Yes. Requiring the use of Omada Cloud-Based Controller"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "300m2(3,200ft2) Recommended Omnidirectional Coverage"],
        ["동시 접속 클라이언트", "380+**"],
        ["무선 표준", "IEEE 802.11be/ax/ac/n/g/b/a"],
        ["주파수", "2.4 GHz, 5 GHz, 6 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) +  4324 Mbps (5 GHz) + 5765 Mbps (6 GHz)†"],
        ["무선 기능", "• 4k-QAM• OFDMA• Multiple SSIDs: 24 (8 for each band)• Enable/Disable Wireless Radio• Automatic Channel Assignment• Transmit Power Control (Adjust Transmit Power on dBm)• QoS (WMM)• MU-MIMO• MLO• 320MHz• Omada Mesh§• Seamless Roaming(802.11k/v/r)§• Band Steering• Load Balance• Airtime Fairness• Beamforming• Rate Limit• Reboot Schedule• Wireless Schedule• Wireless Statistics based on SSID/AP/Client• Static IP/Dynamic lP"],
        ["무선 보안", "• Captive Portal Authentication§• Access Control• Wireless Mac Address Filtering• Wireless Isolation Between Clients• SSID to VLAN Mapping• Rogue AP Detection• 802.1X Support• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise, OWE"],
        ["전송 강도", "• CE:Indoor Mode: < 20 dBm (2.4 GHz, EIRP);, < 23 dBm (5 GHz, band 1 & band 2, ElRP), < 28 dBm (5 GHz, band 3, EIRP); <23dBm (6 GHz, EIRP)Outdoor Mode:  < 20 dBm (2.4 GHz, EIRP); < 28 dBm (5 GHz, band 3, EIRP)• FCC:Indoor Mode: < 25 dBm (2.4 GHz); < 25 dBm (5 GHz); < 25 dBm (6 GHz)Outdoor Mode:< 25 dBm (2.4 GHz); < 25 dBm (5 GHz); < 25 dBm (6 GHz)"],
      ] },
      { title: "기타", rows: [
        ["인증", "CE, FCC, RoHS"],
        ["패키지 구성품", "• Access Point EAP772-Outdoor• Waterproof Kit• Mounting Kits• Installation Guide"],
        ["운영 체제", "Microsoft Windows XP, Vista, Windows 7, Windows 8, Windows10, Windows11, Linux"],
        ["사용 환경", "• Operating Temperature: -30–70 ℃ (-22–158 ℉)• Storage Temperature: -40–70 ℃ (-40–158 ℉)• Operating Humidity: 10–90% RH non-condensing• Storage Humidity: 5–90% RH non-condensing"],
      ] },
    ],
  },
  "EAP773": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap773/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 10G 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "802.3at PoE 또는 12V/2.5A DC참고: 소프트웨어 업데이트로 인해 전원 공급 장치가 802.3bt에서 802.3at로 업데이트되었습니다."],
        ["전력 소모", "• 24.05 W (PoE);• 20.92 W (DC)"],
        ["크기 ( 가로 x 세로 x 높이 )", "8.7 × 8.7 × 1.3 in (220 × 220 × 32.5 mm)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 2× 5.0 dBi• 6 GHz: 2× 5.0 dBi"],
        ["블루투스", "1 × 4.0 dBi, Bluetooth 5.2*펌웨어 업데이트가 필요할 수 있습니다."],
        ["마운트", "천장형/벽면형 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "140㎡(1500 ft²)§"],
        ["동시 접속 클라이언트", "380+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "6 GHz, 5 GHz, 및 2.4 GHz"],
        ["신호 속도", "574 Mbps (2.4 GHz) + 4320 Mbps (5 GHz) + 5760 Mbps (6 GHz)†"],
        ["무선 기능", "• MLO‡• 4K-QAM‡• MU-MIMO‡• HE320‡• 메시Δ• BSS Coloring‡• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID: 24(각 대역당 8개)• 무선 일정• 일정 재부팅• QoS(WMM)• 속도 제한• 고정 IP/동적 IP• RADIUS  Accounting• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증Δ• 액세스 컨트롤• 최대 MAC 필터 수: 4,000• 클라이언트 간 무선 격리• VLAN• 로그 AP 탐지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "< 25 dBm (2.4 GHz)< 25 dBm (5 GHz)< 23 dBm (6 GHz)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "가능"],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러 (OC300)• Omada 하드웨어 컨트롤러 (OC200)• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "가능. OC300, OC200, Omada 소프트웨어 컨트롤러 또는 Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "가능"],
        ["LED 켜기/끄기 제어", "가능"],
        ["관리 MAC 액세스 컨트롤", "가능"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "가능"],
        ["웹기반 관리기능", "가능"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• EAP773• 설치 설명서• 천장/벽면 마운팅 키트참고: 전원 어댑터는 포함되어 있지 않습니다."],
        ["사용 환경", "• 작동 온도: 0 °C–40 °C (32 °F–104 °F);• 보관 온도: -40 °C–70 °C (-40 °F–158 °F);• 작동 습도: 10%–90% 이슬 맺힘이 없는 상태;• 보관 습도: 5%–90% 이슬 맺힘이 없는 상태;"],
      ] },
    ],
  },
  "EAP783": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap783/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "2× 10G 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "• 802.3bt PoE++• 12V DC참고：전원 어댑터는 따로 구매해야 합니다."],
        ["전력 소모", "39W"],
        ["크기 ( 가로 x 세로 x 높이 )", "11.0 x 11.0 x 1.8 in (280 x 280 x 46.5 mm)"],
        ["안테나", "Omni 내부 안테나• 2.4 GHz: 4× 4 dBi• 5 GHz: 4× 5.5 dBi• 6 GHz: 4× 5 dBi"],
        ["블루투스", "가능"],
        ["마운트", "천장/벽면 장착 (키트 포함)"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "200㎡ (2150 ft²)§"],
        ["동시 접속 클라이언트", "760+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "6 GHz, 5 GHz, 2.4 GHz"],
        ["신호 속도", "• 6 GHz: 최대 11520 Mbps• 5 GHz: 최대 8640 Mbps• 2.4 GHz: 최대 1376 Mbps"],
        ["무선 기능", "• MLO• 4K-QAM• 4x4 MU-MIMO DL/UL• HE320  (320 MHz 대역폭)‡• 메시§• AI 로밍△• 자동 채널 선택 및 전력 조정*• BSS 컬러• UL/DL OFDMA• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSID• 무선 통계• 무선 일정• 일정 재부팅• RADIUS Accounting• MAC 인증• 정적 IP/동적 IP"],
        ["무선 보안", "• PPSK• VLAN• 액세스 제어• 로그 AP 감지• 캡티브 포털 인증△• MAC 필터 최대 개수: 4,000• 클라이언트 간 무선 격리• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise, OWE"],
        ["전송 강도", "• FCC: <28 dBm (2.4 GHz)<28 dBm (5G band 1&band 4)<24 dBm (5G band 2&band 3)<28 dBm (6 GHz)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "가능"],
        ["복구 및 백업", "가능"],
        ["웹을 통한 펌웨어 업데이트", "가능"],
        ["NTP", "가능"],
        ["중앙 집중식 관리", "• Omada 하드웨어 컨트롤러 (OC300)• Omada 하드웨어 컨트롤러 (OC200)• Omada 소프트웨어 컨트롤러• Omada 클라우드 기반 컨트롤러"],
        ["클라우스 액세스", "OC300, OC200, Omada 소프트웨어 컨트롤러 또는 Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["이메일 경보", "가능"],
        ["LED 켜기/끄기 제어", "가능"],
        ["관리 MAC 액세스 컨트롤", "가능"],
        ["SNMP", "v1, v2c, v3"],
        ["SSH", "가능"],
        ["웹기반 관리기능", "가능"],
      ] },
      { title: "일반", rows: [
        ["중량", "순중량:1384.6g"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS, IC"],
        ["구성품", "• EAP783• 설치 가이드• 천장, 벽 마운팅 키트"],
        ["환경", "• 작동 온도: 0 °C–40 °C (32 °F–104 °F);• 보관 온도: -40 °C–70 °C (-40 °F–158 °F);• 작동 습도: 10%–90% 이슬 맺힘이 없는 상태;• 보관 습도: 5%–90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "EAP787": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-wifi-ceiling-mount/eap787/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "1× 10G/2.5G 이더넷 포트"],
        ["버튼", "Reset"],
        ["전원 공급", "802.3at/bt PoE 또는 DC 12 V/2.5 A"],
        ["전력 소모", "• 29 W (PoE 전원)• 24.5 W (DC 전원)"],
        ["크기 ( 가로 x 세로 x 높이 )", "220 × 220 × 38.8 mm (8.7 × 8.7 × 1.5 in)"],
        ["안테나", "• 2.4 GHz: 2× 4.0 dBi• 5 GHz: 4× 5.0 dBi• 6 GHz: 2× 5.0 dBi"],
        ["블루투스", "1× 5 dBi (최대 게인, 내장 안테나 모듈*펌웨어 업데이트가 필요할 수도 있습니다."],
        ["마운트", "천장 설치/벽면 설치/정션 박스 설치 (설치 부속품 제공)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원"],
        ["중앙 집중식 관리", "• Omada Central (클라우드 기반)• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 컨트롤러가 필요합니다."],
        ["이메일 경보", "지원"],
        ["LED 켜기/끄기 제어", "지원"],
        ["관리 MAC 액세스 컨트롤", "지원"],
        ["SNMP", "v1, v2c, v3"],
        ["시스템 로깅\t로컬/리모트 시스로그", "지원"],
        ["웹기반 관리기능", "지원"],
      ] },
      { title: "무선 기능", rows: [
        ["커버리지", "190 m² (2050 ft²)*"],
        ["동시 접속 클라이언트", "510+**"],
        ["무선 표준", "IEEE 802.11 a/b/g/n/ac/ax/be"],
        ["주파수", "2.4 GHz, 5 GHz, 6 GHz"],
        ["신호 속도", "688 Mbps (2.4 GHz) + 8648 Mbps (5 GHz) + 5765 Mbps (6 GHz)†"],
        ["무선 기능", "• 320 MHz 대역폭‡• MLO‡• 4K-QAM‡• 멀티 RU‡• 심리스 로밍(802.11k/v/r)• MU-MIMO‡• 메시△• BSS 컬러‡• OFDMA‡• 로드 밸런싱• 밴드 스티어링• 빔포밍• Airtime Fairness• 다중 SSIDS:24개 (대역당 8개)• 무선 일정• 재부팅 일정• QoS (WMM)• 속도 제한• 정적 IP/동적 IP• RADIUS 어카운팅• MAC 인증"],
        ["무선 보안", "• 캡티브 포털 인증△• 액세스 제어• MAC 필터• 클라이언트 간 무선 격리• VLAN• 비인가 AP 감지• WPA-Personal/Enterprise, WPA2-Personal/Enterprise, WPA3-Personal/Enterprise"],
        ["전송 강도", "4-25 dBm (2.4 GHz)7-29 dBm (5 GHz, U-NII-1 & U-NII-3)7-26 dBm (5 GHz, U-NII-2A)7-24 dBm (5 GHz, U-NII-2C)4-23 dBm (6 GHz)"],
      ] },
      { title: "기타", rows: [
        ["인증", "• Wi-Fi Alliance: Wi-Fi 7 (R1), Wi-Fi 6 (R2), Wi-Fi 6E, WPA3-R3, WPA3-Suite B, Enhanced Open 보안• KC, FCC/CE/NCC/VCCI/JRF/BSMI"],
        ["패키지 구성품", "• EAP787• 설치 가이드• 천장/벽면/정션 박스 마운팅 키트참고: 전원 어댑터는제공되지 않습니다."],
        ["사용 환경", "• 작동 온도: 0°C ~ 40°C (32°F ~ 104°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
};
