export const switchSpecs = {
  "SG2008": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access/sg2008/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 8× 10/100/1000 Mbps RJ45 Ports (including 1 PD Port)• Auto-Negotiation/Auto MDI/MDIX"],
        ["팬(Fan) 수량", "Fanless"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "AC/DC Adapter (Input: 100-240V AC; Output: 12V DC/1A) or Obtain Power from PoE Source"],
        ["크기 ( 가로 x 세로 x 높이 )", "8.2×4.9×1.0 in (209×126×26 mm)"],
        ["마운트", "Desktop / Wall-Mounting"],
        ["최대 전력 소모량", "6.4 W (220 V/50 Hz)"],
        ["최대 방열수치", "21.84 BTU/hr (220 V/50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "4.1 Mbit"],
        ["점보 프레임", "9 KB"],
        ["대역폭", "16 Gbps"],
        ["패킷 전달 속도", "11.9 Mpps"],
        ["MAC 주소 테이블", "8K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 802.1p CoS/DSCP priority• 8 priority queues• Priority Schedule Mode: SP (Strict Priority), WRR (Weighted Round Robin)• Queue Weight Config• Bandwidth Control: Port/Flow-based Rating Limit• Smoother Performance• Storm Control: Multiple Control Modes(kbps/ratio), Broadcast/Multicast/Unknown-Unicast Control"],
        ["L2 기능", "• 32 IP Interfaces: Support IPv4/IPv6 Interface• Static Routing: 32 IPv4/IPv6 Static Routes• DHCP Server• DHCP Relay: DHCP Interface Relay, DHCP VLAN Relay• DHCP L2 Relay• Static ARP• Proxy ARP• Gratuitous ARP• Link Aggregation• Spanning Tree Protocol• Loopback Detection• 802.3x Flow Control• Mirroring• Device Link Detect Protocol (DLDP)• 802.1ab LLDP/ LLDP-MED"],
        ["L2 멀티캐스트", "• 511 IPv4, IPv6 shared multicast groups• IGMP Snooping• Multicast VLAN Registration (MVR)• Multicast Filtering• Limited IP Multicast (256 profiles and 16 entries per profile)"],
        ["고급 기능", "• Automatic Device Discovery†• Batch Configuration†• Batch Firmware Upgrading†• Intelligent Network Monitoring†• Abnormal Event Warnings†• Unified Configuration†• Reboot Schedule†"],
        ["VLAN", "• VLAN Group: Max 4K VLAN Groups• 802.1Q tag VLAN• MAC VLAN: 12 Entries• Protocol VLAN• GVRP• Voice VLAN"],
        ["액세스 컨트롤 리스트", "• Support up to 230 entries• Time-based ACL• MAC ACL• IP ACL• IPv6 ACL• Combined ACL• Rule Operation: Permit/Deny• Policy Action: Mirroring, Redirect, Rate Limit, QoS Remark• ACL Rules Binding: Port Binding, VLAN Binding"],
        ["보안", "• IP-MAC-Port Binding• AAA• 802.1X- Port-based authentication- MAC (Host) based authentication- Authentication Method includes PAP/EAP-MD5- MAB- Guest VLAN- Support Radius authentication and accountability• IP/IPv6-MAC Binding- 512 Binding Entries- DHCP Snooping- DHCPv6 Snooping- ARP Inspection- ND Detection• IP Source Guard- 253 Entries- Source IP+Source MAC• IPv6 Source Guard- 183 Entries- Source IPv6 Address+Source MAC• DoS Defend• Static/Dynamic/Permanent Port Security- Up to 64 MAC addresses per port• Broadcast/Multicast/Unicast Storm Control- kbps/ratio control mode• Port Isolation• Secure web management through HTTPS with SSLv3/TLS 1.2• Secure Command Line Interface (CLI) management with SSHv1/SSHv2• IP/Port/MAC-based access control"],
        ["IPv6", "• IPv6 Static Routing and ACL• IPv6 Dual IPv4/IPv6• IPv6 Interface• Multicast Listener Discovery (MLD) Snooping• IPv6 neighbor discovery (ND)• Path maximum transmission unit (MTU) discovery• Internet Control Message Protocol (ICMP) version 6• TCPv6/UDPv6• IPv6 applications: DHCPv6 Client, Ping6, Tracert6, Telnet(v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• Support TP-Link private MIBs• RMON MIB(RFC1757, rmon 1,2,3,9)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "Yes. Requiring the use of Omada Hardware Controller, Omada Cloud-Based Controller, or Omada Software Controller."],
        ["중앙 집중식 관리", "• Omada Cloud-Based Controller• Omada Hardware Controller• Omada Software Controller"],
        ["클라우스 액세스", "Yes. Requiring the use of Omada Hardware Controller, Omada Cloud-Based Controller, or Omada Software Controller."],
        ["제로 터치 프로비저닝", "Yes. Requiring the use of Omada Cloud-Based Controller."],
        ["관리 기능", "• Web-based GUI• Command Line Interface (CLI) through telnet• SNMPv1/v2c/v3• SNMP Trap/Inform• RMON (1,2,3,9 groups)• SDM Template• DHCP/BOOTP Client• Dual Image, Dual Configuration• CPU Monitoring• Cable Diagnostics• EEE• SNTP• System Log"],
      ] },
      { title: "기타", rows: [
        ["인증", "CE, FCC, RoHS"],
        ["구성품", "• SG2008• Power Adapter• Installation Guide• Rubber Feet"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ or Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® or Linux."],
        ["사용 환경", "• Operating Temperature: 0–40 ℃ (32–104 ℉);• Storage Temperature: -40–70 ℃ (-40–158 ℉)• Operating Humidity: 10–90% RH non-condensing• Storage Humidity: 5–90% RH non-condensing"],
      ] },
    ],
  },
  "SG2218": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access/sg2218/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 16× 10/100/1000 Mbps RJ45 포트 (자동 협상/자동 MDI/MDIX)• 2× 기가비트 SFP 슬롯"],
        ["팬(Fan) 수량", "팬리스"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V AC~50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 180 × 44 mm (17.3 × 7.1 × 1.7 in)"],
        ["마운트", "랙 설치 가능"],
        ["최대 전력 소모량", "12.3 W (220 V/50 Hz)"],
        ["최대 방열수치", "41.97 BTU/hr (220 V/50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "36 Gbps"],
        ["패킷 전달 속도", "26.8 Mpps"],
        ["MAC 주소 테이블", "8K"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 802.1p CoS/DSCP 우선순위• 8개의 우선순위 대기열• 우선순위 스케줄 모드-      SP (Strict Priority)-      WRR (Weighted Round Robin)• 대기열 가중치 설정• 대역폭 제어-      포트/흐름 기반 속도 제한• 더 원활한 성능• 스톰 컨트롤-      다중 제어 모드 (kbps/ratio)-      브로드캐스트/멀티캐스트/알 수 없는 유니캐스트 제어"],
        ["L2 기능", "• 16개 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 32개의 IPv4/IPv6 정적 경로 지원• DHCP 서버• DHCP 릴레이-     DHCP 인터페이스 릴레이-     DHCP VLAN 릴레이• DHCP L2 릴레이• 정적 ARP• Proxy ARP• Gratuitous ARP• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링• DLDP• 802.1ab LLDP/ LLDP-MED"],
        ["L2 멀티캐스트", "• 511개의 IPv4, IPv6 공유 멀티캐스트 그룹• IGMP 스누핑• MVR• 멀티캐스트 필터링• 제한된 IP 멀티캐스트 (256개 프로필, 프로필당 16개 항목)"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 구성†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 재부팅 일정†"],
        ["VLAN", "• VLAN 그룹-      최대. 4K VLAN 그룹• 802.1Q tag VLAN• MAC VLAN: 12개 항목• 프로토콜 VLAN• GVRP• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 최대 230개 항목 지원• 시간 기반 ACL• MAC ACL• IP ACL• IPv6 ACL• 결합 ACL• 규칙 작동: 허용/거부• 정책 동작-      미러링-      리디렉션-      속도 제한-      QoS Remark• ACL 규칙 바인딩-      포트 바인딩-      VLAN 바인딩"],
        ["보안", "• IP-MAC-포트 바인딩• AAA• 802.1X-      포트 기반 인증-      MAC(호스트) 기반 인증-      인증 방법: PAP/EAP-MD5-      MAB-      게스트 VLAN-      RADIUS 인증 및 어카운팅 지원• IP/IPv6-MAC 바인딩-      512개 바인딩 항목-      DHCP 스누핑-      DHCPv6 스누핑-      ARP 검사-      ND Detection• 출발지 IP 가드-      253개 항목-      출발지 IP+출발지 MAC• 출발지 IPv6 가드-      183개 항목-      출발지 IPv6 주소+출발지 MAC• DoS 방어• 정적/동적/영구 포트 보안-      포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤-      kbps/ratio 제어 모드• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 보안 웹 관리• SSHv1/SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 정적 라우팅 및 ACL• IPv6 듀얼 IPv4/IPv6• IPv6 인터페이스• MLD 스누핑• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션-      DHCPv6 클라이언트-      Ping6-      Tracert6-      Telnet(v6)-      IPv6 SNMP-      IPv6 SSH-      IPv6 SSL-      Http/Https-      IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원• RMON MIB(RFC1757, rmon 1,2,3,9)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• Telnet을 통한 명령줄 인터페이스 (CLI)• SNMPv1/v2c/v3• SNMP Trap/Inform• RMON(1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SG2218 스위치• 전원 코드• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™, Windows 7/8/10/11, MAC® OS, NetWare®, UNIX®, Linux."],
        ["사용 환경", "• 작동 온도: 0°C ~ 40°C (32°F ~ 104°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SG2428P": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access/sg2428p/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 10/100/1000 Mbps PoE+ RJ45 포트 (자동 협상/자동 MDI/MDIX)• 4× 기가비트 SFP 슬롯"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V AC, 50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3at/af 호환• PoE+ 포트: 24개 (포트당 PoE 출력 최대 30 W)• PoE 전력 공급량: 250 W*"],
        ["크기 ( 가로 x 세로 x 높이 )", "440×220×44 mm (17.3×8.7×1.73 in)"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "301.1 W (110 V/60 Hz) (250 W PD 장치 연결 시)"],
        ["최대 방열수치", "1027.40 BTU/hr (110 V/60 Hz) (250 W PD 장치 연결 시)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "56 Gbps"],
        ["패킷 전달 속도", "41.66 Mpps"],
        ["MAC 주소 테이블", "8K"],
        ["패킷 버퍼 메모리", "4.1 Mbit"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 802.1p CoS/DSCP 우선순위• 8개의 우선순위 대기열• 우선순위 예약 모드: SP (Strict Priority), WRR (Weighted Round Robin)• 대기열 가중치 설정• 대역폭 제어: 포트/흐름 기반 속도 제한• 원활한 성능• 스톰 컨트롤: 다중 제어 모드 (kbps/ratio), 브로드캐스트/멀티캐스트/알 수 없는 유니캐스트 제어"],
        ["L2 기능", "• 32개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 32개의 IPv4/IPv6 정적 경로• DHCP 서버• DHCP 릴레이- DHCP 인터페이스 릴레이- DHCP VLAN 릴레이• DHCP L2 릴레이• 정적 ARP• Proxy ARP• Gratuitous ARP• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링• DLDP (장치 링크 감지 프로토콜)• 802.1ab LLDP/ LLDP-MED"],
        ["L2 멀티캐스트", "• 511개의 IPv4, IPv6 멀티캐스트 그룹 공유• IGMP 스누핑• MVR (Multicast VLAN Registration)• 멀티캐스트 필터링• 제한적 IP 멀티캐스트 (256개 프로필 및 프로필당 16개 항목)"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 구성†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 재부팅 일정†"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 12개 항목• 프로토콜 VLAN• GVRP• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 최대 230개 항목 지원• 시간 기반 ACL• MAC ACL• IP ACL• IPv6 ACL• 결합 ACL• 규칙 작업: 허용/거부• 정책 작업- 미러링- 리디렉션- 속도 제한- QoS Remark• ACL 규칙 바인딩- 포트 바인딩- VLAN 바인딩"],
        ["보안", "• IP-MAC-포트 바인딩• AAA• 802.1X- 포트 기반 인증- MAC (호스트) 기반 인증- 인증 수단에 PAP/EAP-MD5 포함- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• IP/IPv6-MAC 바인딩- 512개의 바인딩 항목- DHCP 스누핑- DHCPv6 스누핑- ARP 검사- ND Detection• 출발지 IP 가드- 253개 항목- 출발지 IP + 출발지 MAC• 출발지 IPv6 가드- 183개 항목- 출발지 IPv6 주소 + 출발지 MAC• DoS 방어• 정적/동적/상시 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/ratio 제어 모드• 포트 격리• SSLv3/TLS 1.2를 사용하는 HTTPS 기반 안전한 웹 관리• Secure Command Line Interface (CLI) management with SSHv1/SSHv2• IP/Port/MAC-based access control"],
        ["IPv6", "• IPv6 정적 라우팅 및 ACL• IPv6 듀얼 IPv4/IPv6• IPv6 인터페이스• MLD (Multicast Listener Discovery) 스누핑• IPv6 ND (Neighbor discovery)• Path MTU (Maximum transmission unit) 탐색• ICMP (Internet Control Message Protocol) version 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 클라이언트, Ping6, Tracert6, Telnet(v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link 사설 MIB 지원• RMON MIB(RFC1757, rmon 1,2,3,9)"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러나 Omada 클라우드 기반 컨트롤러, Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러나 Omada 클라우드 기반 컨트롤러, Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• Telnet을 통한 명령줄 인터페이스 (CLI)• SNMPv1/v2c/v3• SNMP Trap/Inform• RMON (1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SG2428P• 전원선• 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: 0℃ ~ 50℃ (32℉ ~ 122℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SG3428X": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-plus/sg3428x/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 10/100/1000 Mbps RJ45 포트 (자동 협상/자동 MDI/MDIX)• 4× 10 G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "팬리스"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "AC 100-240 V~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 180 × 44 mm (17.3 × 7.1 × 1.7 in)"],
        ["서지 보호", "6 kV"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "23.6 W (110 V/60 Hz)"],
        ["최대 방열수치", "80.52 BTU/h (110 V/60 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "12 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "128 Gbps"],
        ["패킷 전달 속도", "95.23 Mpps"],
        ["MAC 주소 테이블", "16K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP(Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 보다 원활한 성능• 흐름 작업: QoS Remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개 IPv4/IPv6 정적 경로• 정적 ARP: 128개 정적 항목• 512개 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 4,000개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로필, 프로필당 16개 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 펌웨어 일괄 업그레이드†• 지능형 네트워크 모니터링†• 비정상 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능*:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16개, 프로토콜 VLAN 16개• 프라이빗 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• ACL 적용 대상: 포트/VLAN"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- ND 스누핑- 출발지 IPv6 가드: 100개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/ratio/pps 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 기반 보안 웹 관리• SSHv1/SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 클라이언트, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러나 Omada 클라우드 기반 컨트롤러, Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러나 Omada 클라우드 기반 컨트롤러, Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SG3428X 스위치• 전원선• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SG3452X": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-plus/sg3452x/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 48× 10/100/1000 Mbps RJ45 포트 (자동 협상/자동 MDI/MDIX)• 4× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× microUSB 콘솔 포트"],
        ["팬(Fan) 수량", "팬리스"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "AC 100-240 V~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 220 × 44 mm (17.3 × 8.7 × 1.7 in)"],
        ["서지 보호", "6 kV"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "32.72 W (110V/60Hz)"],
        ["최대 방열수치", "111.65 BTU/h (110 V/60 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "12 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "176 Gbps"],
        ["패킷 전달 속도", "130.94 Mpps"],
        ["MAC 주소 테이블", "16K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP(Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 향상된 성능• 흐름 작업: QoS 리마크 (802.1P 리마크, DSCP 리마크)"],
        ["L2 기능", "• 128개 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개 IPv4/IPv6 정적 경로• 정적 ARP: 128개 정적 항목• 512개 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 1000개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• MVR (Multicast VLAN Registration)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로필, 프로필당 16개 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 펌웨어 일괄 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능*:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹: 최대 4,000개 VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16개, 프로토콜 VLAN 16개• 프라이빗 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS 리마크• ACL 적용 대상: 포트/VLAN"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- ND 스누핑- IPv6 출발지 IP 가드: 100개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/ratio/pps 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2 기반 HTTPS를 통한 보안 웹 관리• SSHv1/SSHv2 기반 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD (Multicast Listener Discovery) 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, Telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SG3452X 스위치• 전원선• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃  ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40℃  ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "SG3428XMP": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-plus/sg3428xmp/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 10/100/1000 Mbps RJ45 PoE+ 포트• 4× 10 G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V AC~50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3at/af 준수• PoE+ 포트: 24개 (포트당 PoE 출력 최대 30 W)• 전력 공급량: 384 W*"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 330 × 44 mm (17.3 × 13.0 × 1.7 in)"],
        ["마운트", "랙 설치 가능"],
        ["최대 전력 소모량", "486.2 W (110 V/60 Hz) (384 W PD 장치 연결 시)"],
        ["최대 방열수치", "1658.78 BTU/hr (110 V/60 Hz) (384 W PD 장치 연결 시)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "128 Gbps"],
        ["패킷 전달 속도", "95.23 Mpps"],
        ["MAC 주소 테이블", "16K"],
        ["패킷 버퍼 메모리", "12 Mbit"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8 priority queues• 802.1p CoS/DSCP priority• Queue scheduling: SP (Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 더 원활한 성능• 흐름 작업: QoS remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 512개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 1,000개의 (IPv4, IPv6) IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개의 프로필, 프로필당 16개의 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 구성†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 재부팅 일정†ISP 기능**:• L2PT (2계층 프로토콜 터널링)• 장치 링크 감지 프로토콜 (DLDP)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개의 항목• 프로토콜 VLAN: 16개의 프로토콜 템플릿, 16개의 프로토콜 VLAN• Private VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• 결합 ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개의 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개의 항목• IPv6-MAC-포트 바인딩- 512개의 항목- DHCPv6 스누핑- ND Detection- ND 스누핑- 출발지 IPv6 가드: 100개의 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 제어: kbps/ratio/pps 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- Radius authentication 및 accountability 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2로 HTTPS를 통한 안전한 웹 관리• SSHv1/SSHv2를 통한 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스 (CLI)• SNMPv1/v2c/v3- Trap/Inform- RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SG3428XMP 스위치• 전원 코드• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: 0°C ~ 45°C (32°F ~ 113°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SG3210X-M2": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-pro/sg3210x-m2/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 8× 2.5 Gbps RJ45 포트• 2× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "팬리스 디자인"],
        ["전원 공급", "100-240 V ~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "294 × 180 × 44 mm (11.6 × 7.1 × 1.7 in)"],
        ["마운트", "랙/데스크톱 설치"],
        ["최대 전력 소모량", "• 최대 15.3W @ 220 V/50 Hz, 25°C• 최대 15.0W @ 110 V/60 Hz, 25°C"],
        ["최대 방열수치", "• 51.92 BTU/h (220 V/50 Hz)• 51.03 BTU/h (110 V/60 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "12 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "80 Gbps"],
        ["패킷 전달 속도", "59.52 Mpps"],
        ["MAC 주소 테이블", "16 K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP(엄격한 우선순위), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/플로우 기반 속도 제한• 더욱 안정적인 성능• 플로우 동작: QoS 마킹(802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 32개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 라우트• 정적 ARP: 128개의 정적 엔트리• 512개의 ARP 엔트리• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 511개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로파일 및 프로파일당 16개 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능**:• L2PT (2계층 프로토콜 터널링)• DLDP (장치 링크 감지 프로토콜)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4,000개• 802.1q Tagged VLAN• MAC VLAN: 256개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16개, 프로토콜 VLAN 16개• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS 마킹• 포트/VLAN 기반 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 엔트리- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 엔트리• IPv6-MAC-포트 바인딩- 512개 엔트리- DHCPv6 스누핑- ND 감지- 출발지 IPv6 가드: 100개 엔트리• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/비율 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 보안 웹 관리• SSHv1/SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6 지원• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet(v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러 (내장 버전 5.15.22 이상 필요)• Omada 하드웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)• Omada 소프트웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트 및 Telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3- Trap/Inform- RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SG3210X-M2 스위치• 전원선• RJ45 콘솔 케이블• 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드• 나사"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 50℃ (23℉ ~ 122℉);• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "SG3218XP-M2": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-pro/sg3218xp-m2/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 16× 2.5 Gbps RJ45 포트 (4× PoE++, 12× PoE+)• 2× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V, 50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3af/at/bt 호환• PoE++ 포트 (802.3af/at/bt PoE): 4개, 포트당 최대 90 W*• PoE+ 포트(802.3af/at PoE): 12개, 포트당 최대 30 W• 전력 공급량: 240 W**• 빠른 PoE• 상시 작동 PoE"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 180 × 44 mm (17.3 × 7.1 × 1.7 in)"],
        ["서지 보호", "6 kV"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "291.16 W (110 V/60 Hz)(240 W PD 장치 연결 시)"],
        ["최대 방열수치", "989.94 BTU/h (110 V/60 Hz)(240 W PD 장치 연결 시)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "12 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "120 Gbps"],
        ["패킷 전달 속도", "89.28 Mpps"],
        ["MAC 주소 테이블", "16K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8 priority queues• 802.1p CoS/DSCP priority• Queue scheduling: SP(Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 보다 안정적인 성능• 흐름 작업: QoS Remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 32개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 512개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 511개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개의 프로파일 및 프로파일당 16개의 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능***:• L2PT (2계층 프로토콜 터널링)• 장치 링크 감지 프로토콜 (DLDP)• PPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 256개 항목• 프로토콜 VLAN: 16개의 프로토콜 템플릿, 16개의 프로토콜 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- IPv6 출발지 IP 가드: 100개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/비율 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 기반의 안전한 웹 관리• SSHv1/SSHv2를 통한 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• 멀티캐스트 리스너 탐색(MLD) 스누핑• IPv6 ACL• IPv6 인터페이스• 고정 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러 (내장 버전 5.15.22 이상 필요)• Omada 하드웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)• Omada 소프트웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트 및 Telnet을 통한 명령줄 인터페이스(CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• IEEE 802.3az 에너지 효율 이더넷 (EEE)• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SG3218XP-M2 스위치• 전원선• 콘솔 케이블• 마운팅 브라켓• 고무 미끄럼 방지 패드• 나사• 빠른 설치 가이드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 50℃ (23℉ ~ 122℉);• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "SG3428XPP-M2": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-pro/sg3428xpp-m2/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 2.5 Gbps PoE++ RJ45 포트• 4× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "3"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V ~ 50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3bt/at/af 준수• PoE++ 포트 (802.3af/at/bt PoE): 24개, 포트당 최대 90W• 전력 공급량: 770W• 빠른 PoE• 상시 작동 PoE"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 330 × 44 mm (17.3 × 13.0 × 1.7 in)"],
        ["서지 보호", "6 kV"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "• 900.2 W (110 V/60 Hz, 25 °C) (770 W PD 연결 시)• 946.8 W (220 V/50 Hz, 25 °C) (770 W PD 연결 시)"],
        ["최대 방열수치", "• 3069.68 BTU/hr (110 V/60 Hz, 25 °C) (770 W PD 연결 시)• 3228.59 BTU/hr (220 V/50 Hz, 25 °C) (770 W PD 연결 시)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "16 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "200 Gbps"],
        ["패킷 전달 속도", "148.80 Mpps"],
        ["MAC 주소 테이블", "32 K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 큐• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP(Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 더욱 안정적인 성능• 플로우 작업: QoS Remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 32개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 512개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 511개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개의 프로파일 및 프로파일당 16개의 엔트리"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능***:• L2PT (Layer 2 Protocol Tunneling)• 장치 링크 감지 프로토콜 (DLDP)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4K개 VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 256개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16개, 프로토콜 VLAN 16개• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, 단편화, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 탐지- ND 스누핑- IPv6 출발지 IP 가드: 100개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/ratio/pps 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 기반의 안전한 웹 관리• SSHv1/SSHv2를 통한 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 고정 IPv6 라우팅• IPv6 ND (Neighbor Discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러 중 하나를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러 (내장 버전 5.15.22 이상 필요)• Omada 하드웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)• Omada 소프트웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러 중 하나가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트 및 Telnet을 통한 명령줄 인터페이스(CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SG3428XPP-M2 스위치• 전원선• RJ45 콘솔 케이블• 설치 가이드• 랙 설치 키트• 고무 미끄럼 방지 패드• 나사"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "SX3206HPP": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-max/sx3206hpp/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 4× 100/1000/2500/5000/10000 Mbps RJ45 포트• 2× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× MicroUSB 콘솔 포트"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V AC~ 50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3af/at/bt (유형 3) 호환**• PoE+ 포트: 4개, 포트당 최대 60 W• 총 PoE 공급량: 200 W*"],
        ["크기 ( 가로 x 세로 x 높이 )", "294 × 180 × 44 mm (11.6 × 7.1 × 1.7 in)"],
        ["마운트", "• 랙 설치• 책상 배치"],
        ["최대 전력 소모량", "244.90 W (110 V/60 Hz) (200 W PD 장치 연결시)"],
        ["최대 방열수치", "835.67 BTU/h (110 V/60 Hz) (200 W PD 연결시)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "120 Gbps"],
        ["패킷 전달 속도", "89.28 Mpps"],
        ["MAC 주소 테이블", "32 K"],
        ["패킷 버퍼 메모리", "16 Mbit"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP (Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 보다 원활한 성능• 흐름 작업: QoS remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 512개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 1000개의 (IPv4, IPv6) IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록 (MVR)• MLD 스누핑• 멀티캐스트 필터링: 프로필 256개, 프로필당 항목 16개"],
        ["고급 기능", "• 자동 장치 검색†• 일괄 구성†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 재부팅 일정†ISP 기능***:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• sFlow• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16, 프로토콜 VLAN 16• 프라이빗 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선 순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• 결합 ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개의 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 100개 항목• IPv6-MAC-포트 바인딩- 512개의 항목- DHCPv6 스누핑- ND Detection- ND 스누핑- 출발지 IPv6 가드: 100개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 제어: kbps/ratio/pps 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2 기반 HTTPS를 통해 안전한 웹 관리• SSHv1/SSHv2 기반의 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD(Multicast Listener Discovery) 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (Neighbor discovery)• Path MTU(maximum transmission unit) 검색• ICMP(Internet Control Message Protocol) 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 클라이언트, Ping6, Tracert6, Telnet(v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스(CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON(1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• EEE• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SX3206HPP 스위치• 전원 코드• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: 0℃ ~ 50℃ (32°F ~ 122°F)• 보관 온도: -40℃ ~ 70℃ (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SX3832": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-max/sx3832/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 100M/1G/2.5G/5/10G RJ45 포트 (자동 협상/자동 MDI/MDIX)• 8× 1/10G SFP+ 슬롯**• 1× RJ45 콘솔 포트• 1× USB C타입 콘솔 포트"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 220 × 44 mm (17.3 × 8.7 × 1.7 in)"],
        ["서지 보호", "6 kV"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "104.9 W (@110 V/60 Hz)106.5 W (@220 V/50 Hz)"],
        ["최대 방열수치", "357.81 BTU/hr (@110 V/60 Hz)363.23 BTU/hr (@220 V/50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "24 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "640 Gbps"],
        ["패킷 전달 속도", "240 Mpps"],
        ["MAC 주소 테이블", "32K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP (Strict Priority), WRR (Weighted Round Robin), SP + WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 보다 원활한 성능• 흐름 작업: QoS remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 510개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 4,000개의 (IPv4, IPv6) IGMP 그룹• IGMP 스누핑• IGMP 인증• MVR (Multicast VLAN Registration)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로필, 프로필당 16개 항목"],
        ["고급 기능", "• 자동 장치 탐지†• 일괄 설정†• 펌웨어 일괄 업그레이드†• 지능형 네트워크 모니터링†• 비정상 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 256개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16, 프로토콜 VLAN 12• 프라이빗 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP Flag, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 96개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- ND 스누핑- 출발지 IPv6 가드 : 95개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 제어: kbps/ratio 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2 기반 HTTPS를 통해 안전한 웹 관리• SSHv1/SSHv2 기반의 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD (Multicast Listener Discovery) 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum transmission unit)) 탐색• ICMP (Internet Control Message Protocol) 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 클라이언트, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러, 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러, 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단•  IEEE 802.3az Energy Efficient Ethernet (EEE)• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SX3832 스위치• 전원선• 콘솔 케이블• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 50℃ (23℉ ~ 122℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158 ℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SX3832MPP": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-access-max/sx3832mpp/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 100 Mbps/1 Gbps/2.5 Gbps/5 Gbps/10 Gbps RJ45 포트 (자동 협상/자동 MDI/MDIX)• 8× 1/10G SFP+ 슬롯‡• 1× RJ45 콘솔 포트• 1× USB C타입 콘솔 포트"],
        ["팬(Fan) 수량", "4"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "AC 100-240 V~ 50/60 Hz"],
        ["PoE 포트 (RJ45)", "• 표준: 802.3af/at/bt 호환• PoE++ 포트 (802.3af/at/bt PoE): 24개, 포트당 최대 90 W**• 총 PoE 공급량: 770 W*"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 330 × 44 mm (17.3 × 13.0 × 1.7 in)"],
        ["마운트", "랙 설치 가능"],
        ["최대 전력 소모량", "1,010.2 W (110 V/60 Hz) (770 W PD 장치 연결 시)953.7 W (220 V/50 Hz) (770 W PD 장치 연결 시)"],
        ["최대 방열수치", "3,444.7 BTU/hr (110 V/60 Hz) (770 W PD 연결 시)3,252.2 BTU/hr (220 V/50 Hz) (770 W PD 연결 시)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "640 Gbps"],
        ["패킷 전달 속도", "240 Mpps"],
        ["MAC 주소 테이블", "32K"],
        ["패킷 버퍼 메모리", "24 Mbit"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP (Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 보다 원활한 성능• 흐름 작업: QoS remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 510개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 4,000개의 (IPv4, IPv6) IGMP 그룹• IGMP 스누핑• IGMP 인증• MVR (Multicast VLAN Registration)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로필, 프로필당 16개 항목"],
        ["고급 기능", "• 자동 장치 탐지†• 일괄 설정†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 이상 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM"],
        ["VLAN", "• VLAN 그룹: 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 256개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16, 프로토콜 VLAN 12• 프라이빗 VLAN• GVRP• VLAN VPN: VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP Flag, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드: 96개 항목• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND Detection- ND 스누핑- 출발지 IPv6 가드 : 95개 항목• DoS 방어• DHCP 필터• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 제어: kbps/ratio 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2 기반 HTTPS를 통해 안전한 웹 관리• SSHv1/SSHv2 기반의 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD(Multicast Listener Discovery) 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum transmission unit)) 탐색• ICMP (Internet Control Message Protocol) 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 클라이언트, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스(CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON(1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• IEEE 802.3az Energy Efficient Ethernet (EEE)• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SX3832MPP스위치• 전원선• 콘솔 케이블• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40℃ ~ 70℃ (-40℉ ~ 158 ℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SX3008F": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-aggregation/sx3008f/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 8× 10 GE SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "팬리스"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "100-240 V AC~50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 180 × 44 mm (17.3 × 7.1 × 1.7 in)"],
        ["마운트", "랙 설치 가능"],
        ["최대 전력 소모량", "15.46 W (220 V / 50 Hz)"],
        ["최대 방열수치", "52.75 BTU/hr (220 V / 50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["스위칭 용량", "160 Gbps"],
        ["패킷 전달 속도", "119.04 Mpps"],
        ["MAC 주소 테이블", "32 K"],
        ["패킷 버퍼 메모리", "16 Mbit"],
        ["점보 프레임", "9 KB"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8 priority queues• 802.1p CoS/DSCP priority• Queue scheduling: SP (Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 더 원활한 성능• 흐름 작업: QoS remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개의 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개의 IPv4/IPv6 정적 경로• 정적 ARP: 128개의 정적 항목• 512개의 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 1,000개 (IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록(MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개의 프로필, 프로필당 16개의 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 구성†•  일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 재부팅 일정†ISP 기능*:• L2PT (2계층 프로토콜 터널링)• 장치 링크 감지 프로토콜 (DLDP)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹 (802.1q VLAN): 최대 4K VLAN 그룹• 802.1Q Tagged VLAN• MAC VLAN: 30개의 항목• 프로토콜 VLAN: 16개의 프로토콜 템플릿 , 12개의 프로토콜 VLAN• 사설 VLAN• GVRP• VLAN VPN (QinQ): 포트 기반 QinQ, 선택적 QinQ• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• 결합 ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩-   512개의 항목-   DHCP 스누핑-   ARP 검사-   출발지 IPv4 가드• IPv6-MAC-포트 바인딩-   512개의 항목-   DHCPv6 스누핑-   ND Detection-   ND 스누핑-   출발지 IPv6 가드• DoS 방어• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 제어: kbps/ratio 제어 모드• 802.1X-   포트 기반 인증-   MAC 기반 인증-    VLAN 할당-    MAB-   게스트 VLAN-    RADIUS authentication and accountability 지원•  AAA(TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2로 HTTPS를 통한 안전한 웹 관리• SSHv1/SSHv2를 통한 안전한 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "MIB II(RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB(RFC2674)• RMON MIB (RFC2819)• RMON2 MIB(RFC2021)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러• Omada 하드웨어 컨트롤러• Omada 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON(1,2,3,9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["구성품", "• SX3008F 스위치• 전원 코드• 빠른 설치 가이드• 랙 설치 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: 0°C ~ 50°C (32°F ~ 122°F)• 보관 온도: -40°C ~ 70°C (-40°F ~ 158°F)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "SX3016F": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-aggregation/sx3016f/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 16× 10G SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "1"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "• 1+1 전원 이중화 (내장형 고정식)• 100–240 V~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 220 × 44 mm (17.3 × 8.7 × 1.7 in)"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "• 최대 32.3 W @ 220 V/50 Hz 25°C• 최대 32.7 W @ 110 V/60 Hz 25°C"],
        ["최대 방열수치", "• 110 BTU/hr (220 V/50 Hz)• 111.18 BTU/hr (110 V/60 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "24 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "320 Gbps"],
        ["패킷 전달 속도", "238.08 Mpps"],
        ["MAC 주소 테이블", "32K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8개의 우선순위 대기열• 802.1p CoS/DSCP 우선순위• 대기열 스케줄링: SP(Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 더욱 안정적인 성능• 흐름 작업: QoS Remark (802.1p Remark, DSCP Remark)"],
        ["L2 기능", "• 128개 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개 IPv4/IPv6 정적 경로• 정적 ARP: 128개 정적 항목• 512개 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 4,000개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록 (MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개의 프로필 및 프로필당 16개의 항목"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 펌웨어 일괄 업그레이드†• 지능형 네트워크 모니터링†• 비정상 이벤트 경고†• 통합 설정†• 재부팅 일정†ISP 기능*:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹 (802.1q VLAN): 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개 항목• 프로토콜 VLAN: 프로토콜 템플릿 16개, 프로토콜 VLAN 12개• 프라이빗 VLAN• GVRP• VLAN VPN (QinQ): 포트 기반 QinQ, 선택적 QinQ• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- ND 스누핑- 출발지 IPv6 가드• DoS 방어• 정적/동적 포트 보안: 포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/비율 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 보안 웹 관리• SSHv1/SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD (Multicast Listener Discovery) 스누핑• IPv6 ACL• IPv6 인터페이스• 정적 IPv6 라우팅• IPv6 ND (neighbor discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• Radius Accounting Client MIB (RFC2620)• Radius Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러 (내장 버전 5.15.22 이상 필요)• Omada 하드웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)• Omada 소프트웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, Telnet을 통한 명령줄 인터페이스(CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SX3016F 스위치• 전원선• 콘솔 케이블• 랙마운트 키트• 고무 미끄럼 방지 패드• 빠른 설치 가이드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40 ℃ ~ 70 ℃ (-40 ℉ ~ 158 ℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "SX3032F": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-aggregation/sx3032f/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 32× 1/10Gbps SFP+ 슬롯• 1× RJ45 콘솔 포트• 1× Micro USB 콘솔 포트"],
        ["팬(Fan) 수량", "2"],
        ["물리적 보안 잠금 장치", "√"],
        ["전원 공급", "• 1+1 전원 이중화 (내장형 고정식)• 100-240 V~ 50/60 Hz"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 330 × 44 mm (17.3 × 13.0 × 1.7 in)"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "49.4 W (220 V / 50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "24 Mbit"],
        ["점보 프레임", "9 KB"],
        ["스위칭 용량", "640 Gbps"],
        ["패킷 전달 속도", "240 Mpps"],
        ["MAC 주소 테이블", "32 K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• 8 priority queues• 802.1p CoS/DSCP priority• Queue scheduling: SP (Strict Priority), WRR (Weighted Round Robin), SP+WRR• 대역폭 제어: 포트/흐름 기반 속도 제한• 더 부드러운 성능• 흐름 작업: QoS Remark (802.1P Remark, DSCP Remark)"],
        ["L2 기능", "• 128개 IP 인터페이스: IPv4/IPv6 인터페이스 지원• 정적 라우팅: 48개 IPv4/IPv6 정적 경로• 정적 ARP: 128개 정적 항목• 510개 ARP 항목• Proxy ARP• Gratuitous ARP• DHCP 서버• DHCP 릴레이: DHCP 인터페이스 릴레이, DHCP VLAN 릴레이• DHCP L2 릴레이• 링크 어그리게이션• 스패닝 트리 프로토콜• 루프백 감지• 802.3x 흐름 제어• 미러링"],
        ["L2 멀티캐스트", "• 4,000개(IPv4, IPv6)의 IGMP 그룹 지원• IGMP 스누핑• IGMP 인증• 멀티캐스트 VLAN 등록 (MVR)• MLD 스누핑• 멀티캐스트 필터링: 256개 프로필, 프로필당 16개 엔트리"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 설정†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 통합 설정†• 재부팅 일정†ISP 기능*:• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• PPPoE ID 삽입• ERPS• 802.3ah 이더넷 링크 OAM• DDM• sFlow"],
        ["VLAN", "• VLAN 그룹 (802.1q VLAN): 최대 4K VLAN 그룹• 802.1q Tagged VLAN• MAC VLAN: 30개 항목• 프로토콜 VLAN• GVRP• VLAN VPN (QinQ): VLAN Mapping, VLAN Replace• 음성 VLAN"],
        ["액세스 컨트롤 리스트", "• 시간 기반 ACL• MAC ACL: 출발지 MAC, 목적지 MAC, VLAN ID, 사용자 우선순위, Ether Type• IP ACL: 출발지 IP, 목적지 IP, Fragment, IP 프로토콜, TCP 플래그, TCP/UDP 포트, DSCP/IP TOS• Combined ACL• 패킷 콘텐츠 ACL• IPv6 ACL• 정책: 미러링, 리디렉션, 속도 제한, QoS Remark• 포트/VLAN에 ACL 적용"],
        ["보안", "• IP-MAC-포트 바인딩- 512개 항목- DHCP 스누핑- ARP 검사- 출발지 IPv4 가드• IPv6-MAC-포트 바인딩- 512개 항목- DHCPv6 스누핑- ND 감지- ND 스누핑- IPv6 출발지 IP 가드• DoS 방어• 정적/동적 포트 보안: 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/유니캐스트 스톰 컨트롤: kbps/비율 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• 포트 격리• SSLv3/TLS 1.2를 통한 HTTPS 기반 보안 웹 관리• SSHv1/SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어"],
        ["IPv6", "• IPv6 듀얼 IPv4/IPv6• MLD 스누핑• IPv6 ACL• IPv6 인터페이스• 고정 IPv6 라우팅• IPv6 ND (Neighbor Discovery)• Path MTU (Maximum Transmission Unit) 탐색• ICMP 버전 6• TCPv6/UDPv6• IPv6 애플리케이션: DHCPv6 Client, Ping6, Tracert6, Telnet (v6), IPv6 SNMP, IPv6 SSH, IPv6 SSL, Http/Https, IPv6 TFTP"],
        ["MIBs", "• MIB II (RFC1213)• Interface MIB (RFC2233)• Ethernet Interface MIB (RFC1643)• Bridge MIB (RFC1493)• P/Q-Bridge MIB (RFC2674)• RMON MIB (RFC2819)• RMON2 MIB (RFC2021)• RADIUS Accounting Client MIB (RFC2620)• RADIUS Authentication Client MIB (RFC2618)• Remote Ping, Traceroute MIB (RFC2925)• TP-Link private MIB 지원"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["중앙 집중식 관리", "• Omada 클라우드 기반 컨트롤러 (내장 버전 5.15.22 이상 필요)• Omada 하드웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)• Omada 소프트웨어 컨트롤러 (내장 버전 5.15.20 이상 필요)"],
        ["클라우스 액세스", "지원. Omada 하드웨어 컨트롤러, Omada 클라우드 기반 컨트롤러 또는 Omada 소프트웨어 컨트롤러가 필요합니다."],
        ["제로 터치 프로비저닝", "지원. Omada 클라우드 기반 컨트롤러가 필요합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트 및 Telnet을 통한 명령줄 인터페이스 (CLI)• SNMP v1/v2c/v3: Trap/Inform, RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 비밀번호 복구• SNTP• 시스템 로그"],
      ] },
      { title: "기타", rows: [
        ["인증", "KC, CE, FCC, RoHS"],
        ["패키지 구성품", "• SX3032F 스위치• 전원선• 콘솔 케이블• 랙마운트 키트• 고무 미끄럼 방지 패드• 빠른 설치 가이드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도: -5℃ ~ 45℃ (23℉ ~ 113℉)• 보관 온도: -40 ℃ ~ 70 ℃ (-40 ℉ ~ 158 ℉)• 작동 습도: 10% ~ 90% RH (이슬 맺힘이 없는 상태)• 보관 습도: 5% ~ 90% RH (이슬 맺힘이 없는 상태)"],
      ] },
    ],
  },
  "S6500-24G4XF": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-campus/s6500-24g4xf/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 10/100/1000 Mbps RJ45 포트• 4× 1/10 Gbps SFP+ 슬롯*• 2× USB 2.0 포트• 1× RJ45 콘솔 포트• 1× USB C타입 콘솔 포트• 1× RJ45 관리 포트"],
        ["팬(Fan) 수량", "4× 내부 고정 팬"],
        ["전원 공급", "2× 내부 고정 전원 공급 모듈 (100–240 VAC, 50/60 Hz)"],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 380 × 44 mm (17.3 × 15.0 × 1.7 in)"],
        ["마운트", "랙 설치"],
        ["최대 전력 소모량", "28.4 W (220 V/50 Hz)"],
        ["최대 방열수치", "96.91 BTU/hr (220 V/50 Hz)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "3 MB"],
        ["점보 프레임", "9 KB"],
        ["스태킹", "• 스태킹 수: 12 (독립 실행형 모드)• 스태킹 포트: 10G SFP+ 슬롯 (모든 업링크 포트를 스태킹 포트로 사용할 수 있음)**• 스택 대역폭: 최대 80 Gbps (4개의 스태킹 포트)"],
        ["스위칭 용량", "장치당 128 Gbps"],
        ["패킷 전달 속도", "95.2 Mpps"],
        ["MAC 주소 테이블", "32 K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• Cos (Class of Service)-    8개의 우선순위 대기열-    포트 우선순위-    IEEE 802.1p 우선순위-    DSCP 우선순위-    최소 대기열 대역폭-    일정 예약 모드(SP, WRR, SP+WRR)• 대역폭 제어-    속도 제한-    스톰 제어• 음성 VLAN• 사용자 정의 OUI• 원활한 성능• 흐름 작업-    QoS remark (802.1P Remark, DSCP Remark)• WRED 프로필: 16"],
        ["L3 기능", "• L3 인터페이스: 256 (IPv4,IPv6)• 정적 경로: 1,024 IPv4, 512 IPv6• 호스트 경로 테이블: 최대 6,100개 항목• IPv4 네트워크 라우터 항목: 10,240 (IPv6 네트워크 라우터 항목과 공유)• IPv6 네트워크 라우터 항목: 5,120 (IPv4 네트워크 라우터 항목과 공유)• ECMP: 256개 항목, 목적지당 최대 32개의 ECMP 넥스트 홉• 정적 ARP: 512개의 정적 항목• 동적 ARP: 7,680개의 동적 항목• ND: 7680• DHCP 서버: 최대 64개의 IP 풀, 최대 8,000개의 IP 항목• DHCPv4/v6 릴레이• VRRP: 버전 v2/v3, 최대 64개 인스턴스, 인스턴스당 최대 32개의 가상 IP• OSPFv2-    OSPF 인스턴스: 16-    네트워크 항목: 256개 항목-    Stub 또는 NSSA에 대한 영역 항목: 인스턴스당 16개-    영역 범위 항목: 인스턴스당 16개-    가상 링크 항목: 인스턴스당 16개• OSPFv3-    Stub 또는 NSSA에 대한 영역 항목: 인스턴스당 16개-    영역 범위 항목: 인스턴스당 16개• RIPv1/v2-    네트워크 항목: 256-    항목 재분배: 20• RIPng• IS-IS-     IS-IS 인터페이스: 128-    IS-IS 영역 번호: 3-    최대 설정 재분배: 10-    IS-IS IPV6-    IS-IS BFD• BGP: 최대 20개의 재분배 설정• PIM-SM/PIM-DM/PIM-SSM-    IP 멀티캐스트 경로 항목: 1K-    PIM Neighbors: 256-    최대 PIM 인터페이스: 128• IGMP: 버전 v1/v2/v3, 최대 2,048개의 멀티캐스트 그룹• BFD: 16개의 템플릿 번호, 8개의 세션 번호• PBR• uRPF"],
        ["L2 기능", "• 링크 어그리게이션• 스패닝 트리 프로토콜• 포트 기반 및 VLAN 기반 루프백 감지• 802.3x 흐름 제어• ERPS• 미러링• RSPAN• MAC 주소 테이블• 멀티캐스트-    IGMP 스누핑-     MLD 스누핑-     MVR-    최대 멀티캐스트 테이블: 4K (IPv4, IPv6)-    Fast Leave-    정적 멀티캐스트 그룹-    멀티캐스트 필터링-    IGMP 스누핑 인증"],
        ["고급 기능", "• 자동 장치 탐색†• 일괄 구성†• 일괄 펌웨어 업그레이드†• 지능형 네트워크 모니터링†• 비정상적인 이벤트 경고†• 통합 구성†• 일정 재부팅†ISP 기능:• 802.3ah 이더넷 링크 OAM• L2PT• DLDP• DDM• sFlow"],
        ["VLAN", "• 최대 4,000개의 VLAN 그룹 (802.1q VLAN)• 802.1Q Tagged VLAN• MAC VLAN 항목: 200개• 멀티캐스트 VLAN• 관리 VLAN• VLAN VPN (QinQ): 최대 256개 항목• GVRP• 프로토콜 VLAN: 프로토콜 템플릿 16, 프로토콜 VLAN 12 항목• 음성 VLAN• 프라이빗 VLAN"],
        ["보안", "• 포트 격리• CPU 방어• ARP 검사 (동적 ARP 검사)• DoS 방어• IP-MAC-포트 바인딩-    1,024개 항목-    DHCP 스누핑-    ARP 검사-    출발지 IPv4 가드• IPv6-MAC-포트 바인딩-   1,024 항목-    DHCPv6 스누핑-    ND Detection-    ND 스누핑-    출발지 IPv6 가드• DHCP 필터• 정적/동적 포트 보안-   포트당 최대 64개의 MAC 주소• 브로드캐스트/멀티캐스트/알 수 없는 유니캐스트 스톰 제어-    kbps/ratio 제어 모드• 802.1X-    포트 기반 인증-    Mac 기반 인증-    VLAN 할당-    MAB-    게스트 VLAN-    RADIUS authentication 및 accountability 지원• AAA (TACACS+ 포함)• SSLv3/TLS 1.2를 통한 안전한 HTTPS 웹 관리 1.2• SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어• MACSec (-128, -256)• 보안 부팅• RADSEC"],
        ["가상화", "• IP 터널-    IPv6 over IPv4-    IPv6 over IPv4 GRE-    IPv4 over IPv4 GRE-    터널 항목: 100"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원, Omada Pro 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada Pro 클라우드 기반 컨트롤러• Omada Pro 하드웨어 컨트롤러• Omada Pro 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원, Omada Pro 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원, Omada Pro 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, Telnet을 통한 명령줄 인터페이스(CLI)• SNMPv1/v2c/v3-   Trap/Inform-   RMON(1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 듀얼 설정• CPU 모니터링• 케이블 진단• 비밀번호 복구• SNTP• 시스템 로그• IEEE 802.3az EEE (Energy Efficient Ethernet)• 구성 롤백(Configuration Rollback)• 핫 패칭(Hot Patching)• NETCONF"],
      ] },
      { title: "기타", rows: [
        ["패키지 구성품", "• S6500-24G4XF 스위치• 2× 전원 코드• RJ45 콘솔 케이블• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™, Windows 7/8/10/11, MAC® OS, NetWare®, UNIX®, Linux."],
        ["사용 환경", "• 작동 환경-5°C ~ 50°C (23°F ~ 122°F)@300 m-5°C ~ 45°C (23°F ~ 113°F)@2,000 m-5°C ~ 40°C (23°F ~ 104°F)@3,000 m• 보관 온도: -40°C ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
  "S6500-24MPP4Y": {
    officialUrl: "https://www.omadanetworks.com/kr/business-networking/omada-switch-campus/s6500-24mpp4y/",
    sections: [
      { title: "하드웨어 사양", rows: [
        ["인터페이스 및 주요 사양", "• 24× 100 Mbps/1 Gbps/2.5 Gbps PoE++ RJ45 포트• 4× 1/10/25G SFP28 슬롯***• 2× USB 2.0 포트• 1× RJ45 콘솔 포트• 1× USB C타입 콘솔 포트• 1× RJ45 관리 포트"],
        ["팬(Fan) 수량", "현장 교체와 핫 스왑을 지원하는 팬 4개"],
        ["전원 공급", "현장 교체 및 핫 스왑을 지원하는 전원 공급 모듈 2개** (100 ~ 240 VAC, 50/60 Hz)**배송 시 PSM900-AC 모듈 1개가 기본으로 탑재되며, 현장 교체 가능한 추가 전원 공급 장치는 별도로 구매해야 합니다."],
        ["PoE 포트 (RJ45)", "• 표준: 802.3af/at/bt 준수• PoE++ 포트: 24개, 포트당 최대 60 W• PoE 전원 공급량: 최대 1440 W**총 PoE 공급량은 전원 공급 모듈에 따라 달라집니다."],
        ["크기 ( 가로 x 세로 x 높이 )", "440 × 420 × 44 mm (17.3 × 16.5 × 1.7 in)"],
        ["마운트", "랙 설치 가능"],
        ["최대 전력 소모량", "• 94.8 W (110 V/60 Hz) (PD 장치 미연결 시)• 1,745.5 W (110 V/60 Hz) (1440 W PD 장치를 연결하고 PSM900-AC 2개로 전원을 공급하는 경우)"],
        ["최대 방열수치", "• 323.3 BTU/hr (110 V/60 Hz) (PD 장치 미연결 시)• 5,952.2 BTU/hr (110 V/60 Hz) (1440 W PD 장치를 연결하고 PSM900-AC 2개로 전원을 공급하는 경우)"],
      ] },
      { title: "성능", rows: [
        ["패킷 버퍼 메모리", "3 MB"],
        ["점보 프레임", "9 KB"],
        ["스태킹", "• 스태킹 수량: 12개 (독립 실행형 모드)• 스태킹 포트: 25G SFP28 슬롯 (모든 업링크 포트를 스태킹 포트로 사용할 수 있음)****• 스택 대역폭: 최대 200 Gbps (4× 스태킹 포트)"],
        ["스위칭 용량", "장치당 320 Gbps"],
        ["패킷 전달 속도", "238.1 Mpps"],
        ["MAC 주소 테이블", "32 K"],
      ] },
      { title: "소프트웨어 기능", rows: [
        ["서비스 품질(QoS)", "• Cos (Class of Service)-   8개의 우선순위 대기열-   포트 우선순위-   IEEE 802.1p 우선순위-   DSCP/ToS 우선순위-   대기열 최소 대역폭-   스케줄 모드(SP, WRR, SP+WRR)• 대역폭 제어-   속도 제한-   스톰 제어• 음성 VLAN• 사용자 정의 OUI• 원활한 성능• 흐름 작업• QoS Remark (802.1P Remark, DSCP Remark)• WRED 프로필: 16"],
        ["L3 기능", "• L3 인터페이스: 256개 (IPv4,IPv6)• 정적 경로: IPv4 1,024개, IPv6 512개• 호스트 경로 테이블: 최대 6,100개 항목• IPv4 네트워크 라우터 항목: 10,240개 (IPv6 네트워크 라우터 항목과 공유)• IPv6 네트워크 라우터 항목: 5,120 (IPv4 네트워크 라우터 항목과 공유)• ECMP: 256개 항목, 목적지당 최대 32 ECMP 넥스트홉• 정적 ARP: 512개 정적 항목• 동적 ARP: 12,288개 동적 항목• ND: 12,288• DHCP 서버: 최대 IP 풀 수: 64, 최대 임대: 8000• DHCPv4/v6 릴레이• VRRP: 버전 v2/v3, 최대 64개 인스턴스, 인스턴스당 최대 32개 가상 IP• OSPFv2- OSPF 프로세스: 16- Graceful Restart- OSPFv2 BFD• OSPFv3- OSPFv3 인스턴스: 1- OSPFv3 BFD• RIPv1/v2• RIPng• IS-ISv4/v6• IS-IS BFD• BGPv4• PIM-SM/PIM-DM/PIM-SSM- IP 멀티캐스트 경로 항목: 1024개• IGMP: 버전 v1/v2/v3, 최대 2,048개 멀티캐스트 그룹• BFD: 16개 템플릿 수, 8개 세션 수• PBR• uRPF"],
        ["L2 기능", "• 링크 어그리게이션• 스패닝 트리 프로토콜• 포트 기반 및 VLAN 기반 루프백 감지• 802.3x 흐름 제어• ERPS• 미러링• RSPAN• MAC 주소 테이블• 멀티캐스트- IGMP 스누핑- MLD 스누핑- Multicast VLAN Registration (MVR)- 최대 멀티캐스트 그룹: 4K (IGMP 스누핑 및 MLD 스누핑 & MVR)- Fast Leave- 정적 멀티캐스트 그룹- 멀티캐스트 필터링- IGMP 스누핑 인증"],
        ["고급 기능", "• 자동 장치 탐색‡• 일괄 구성‡• 일괄 펌웨어 업그레이드‡• 지능형 네트워크 모니터링‡• 비정상적인 이벤트 경고‡• 통합 구성‡• 재부팅 일정‡ISP 기능:• 802.3ah 이더넷 링크 OAM• L2PT (Layer 2 Protocol Tunneling)• DLDP (Device Link Detect Protocol)• DDM• sFlow"],
        ["VLAN", "• 최대 4,000개의 VLAN 그룹(802.1q VLAN)• 802.1Q Tagged VLAN• MAC VLAN 항목: 200• 멀티캐스트 VLAN• 관리 VLAN• VLAN VPN (QinQ):최대 256개 항목• GVRP• 프로토콜 VLAN: 프로토콜 템플릿 16, 프로토콜 VLAN 12 항목• 음성 VLAN• Private VLAN"],
        ["보안", "• 포트 격리• CPU 방어• DoS 방어• IP-MAC 바인딩-1,024개 항목- DHCP 스누핑- ARP 스캐닝• IPv6-MAC 바인딩-1,024개 항목- DHCPv6 스누핑- ND 스누핑• ARP 검사• ND Detection• 출발지 IPv4 가드• 출발지 IPv6 가드• DHCP 필터• 정적/동적 포트 보안- 포트당 최대 64개 MAC 주소• 브로드캐스트/멀티캐스트/알 수 없는-유니캐스트 스톰 제어- kbps/ratio 제어 모드• 802.1X- 포트 기반 인증- MAC 기반 인증- VLAN 할당- MAB- 게스트 VLAN- RADIUS 인증 및 어카운팅 지원• AAA (TACACS+ 포함)• SSLv3/TLS를 사용한 HTTPS를 통한 보안 웹 관리 1.2• SSHv2를 통한 보안 명령줄 인터페이스(CLI) 관리• IP/포트/MAC 기반 액세스 제어• MACSec (gcm-aes-128, gcm-aes-256)• Secure boot• RADSEC"],
      ] },
      { title: "관리", rows: [
        ["Omada 앱", "지원. Omada Pro 컨트롤러를 사용해야 합니다."],
        ["중앙 집중식 관리", "• Omada Pro 클라우드 기반 컨트롤러• Omada Pro 하드웨어 컨트롤러• Omada Pro 소프트웨어 컨트롤러"],
        ["클라우스 액세스", "지원. Omada Pro 컨트롤러를 사용해야 합니다."],
        ["제로 터치 프로비저닝", "지원. Omada Pro 클라우드 기반 컨트롤러를 사용해야 합니다."],
        ["관리 기능", "• 웹 기반 GUI• 콘솔 포트, telnet을 통한 명령줄 인터페이스 (CLI)• SNMPv1/v2c/v3-   Trap/Inform-   RMON (1, 2, 3, 9 그룹)• SDM 템플릿• DHCP/BOOTP 클라이언트• 802.1ab LLDP/LLDP-MED• DHCP 자동 설치• 듀얼 이미지, 이중 구성• CPU 모니터링• 케이블 진단• 비밀번호 복구• SNTP• 시스템 로그• IEEE 802.3az Energy Efficient Ethernet (EEE)"],
      ] },
      { title: "기타", rows: [
        ["패키지 구성품", "• S6500-24MPP4Y 스위치• 전원선• RJ45 콘솔 케이블• 빠른 설치 가이드• 랙마운트 키트• 고무 미끄럼 방지 패드"],
        ["운영 체제", "Microsoft® Windows® 98SE, NT, 2000, XP, Vista™ 또는 Windows 7/8/10/11, MAC® OS, NetWare®, UNIX® 또는 Linux."],
        ["사용 환경", "• 작동 온도:-5°C ~ 45°C (23°F ~ 113°F)@2,000 m-5°C ~ 40°C (23°F ~ 104°F)@3,000 m• 보관 온도: -40°C ~ 70℃ (-40℉ ~ 158℉)• 작동 습도: 10% ~ 90% RH 이슬 맺힘이 없는 상태• 보관 습도: 5% ~ 90% RH 이슬 맺힘이 없는 상태"],
      ] },
    ],
  },
};
