import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Badge from "@/components/ds/Badge";
import { createPageMetadata } from "@/lib/seo";
export const metadata=createPageMetadata({path:"/docs/einsguard-ai/admin",title:"EINSGUARD AI 1.0 관리자 운영 매뉴얼 | EINSTECH",description:"AI 자산 승인, 차단, Shadow AI 사건, 보안 알림, 라이선스와 감사 운영 절차입니다."});
const Title=({n,children})=><h2 className="font-display text-3xl font-black"><span className="mr-3 text-blue-700">{n}</span>{children}</h2>;
const Box=({title,children,warn=false})=><div className={`rounded-xl border p-5 ${warn?"border-amber-400 bg-amber-50":"border-slate-300 bg-white"}`}><b>{title}</b><div className="mt-2 text-slate-700">{children}</div></div>;
export default function AdminGuide(){return <><Header/><main className="bg-slate-50 pt-16 text-slate-900"><section className="border-b border-slate-300 bg-white py-20"><div className="mx-auto max-w-5xl px-6"><Badge>ADMIN OPERATIONS · 1.0</Badge><h1 className="mt-6 font-display text-5xl font-black">관리자 운영 매뉴얼</h1><p className="mt-5 max-w-3xl text-base leading-8 text-slate-600">승인·차단·사건 처리·라이선스·감사 절차를 실제 메뉴 기준으로 정리했습니다.</p></div></section><article className="mx-auto max-w-5xl space-y-16 px-6 py-16 text-sm leading-7">
<section><Title n="1">일일 점검</Title><div className="mt-5 grid gap-4 md:grid-cols-2"><Box title="개요">온라인 Client, 고위험 알림, 승인 대기, 활성 세션을 확인합니다.</Box><Box title="AI 자산">오프라인 Client, 신규 등록, 사용 중 AI와 Shadow AI 사건을 확인합니다.</Box><Box title="보안 알림">High → Med → Low 순으로 검토합니다.</Box><Box title="라이선스">남은 기간과 관리 대상 수를 확인합니다.</Box></div></section>
<section><Title n="2">AI 상태 읽기</Title><div className="mt-5 space-y-3"><Box title="파란색 · ● 사용 중">승인된 AI가 현재 실행 중입니다.</Box><Box title="빨간색 · ● 사용 중 · 차단 대상">미승인 AI 실행이 감지됐습니다.</Box><Box title="녹색 · ✓ 승인">사용은 허용됐지만 현재 실행 중은 아닙니다.</Box><Box title="회색 · 설치됨">설치 흔적은 있지만 승인·실행 상태가 아닙니다.</Box></div><Box title="자동 갱신" warn>Agent 약 5초, 대시보드 약 15초 주기로 갱신합니다. 오프라인 PC는 재연결 후 정책이 반영됩니다.</Box></section>
<section><Title n="3">Agent 등록과 AI 승인</Title><Box title="신규 Agent 등록 승인">Windows 또는 Linux에서 관리 서버 주소를 입력하면 AI 자산에 등록 요청이 표시됩니다. 호스트명·사용자·IP·운영체제를 확인한 뒤 승인합니다. 승인된 Agent는 장비 전용 연결 키를 자동 수령하므로 키를 사용자에게 전달하지 않습니다.</Box><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6"><li>AI 자산 → Client 검색 → 대상 AI 배지를 클릭해 승인합니다.</li><li>승인된 배지를 다시 클릭하면 승인 해제됩니다.</li><li>승인 해제 후 Agent가 정책을 받으면 실행 중 앱·CLI를 종료하고 웹 AI를 차단합니다.</li><li>5~20초 뒤 상태 배지와 Shadow AI 이벤트를 확인합니다.</li></ol><Box title="주의" warn>Agent 등록 요청은 호스트명·사용자·IP·운영체제를 모두 확인한 뒤 승인하십시오. AI 승인 해제는 사용자의 실행 중 작업을 종료할 수 있으므로 사용자와 업무 영향을 먼저 확인하십시오.</Box></section>
<section><Title n="4">에이전트 제거 승인</Title><Box title="개요">사용자는 에이전트를 임의로 제거할 수 없습니다. 장비에서 제거를 실행하면 관리 서버로 요청이 오고, 관리자가 승인해야 제거됩니다.</Box><div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-slate-300 bg-white p-6"><b>요청 승인 (기본)</b><ol className="mt-3 space-y-2 text-slate-700"><li><b>1.</b> ‘관리자 처리할 일’ 또는 장비·사용자 화면의 ‘에이전트 제거 승인’ 요청을 엽니다.</li><li><b>2.</b> 호스트명·사용자·IP·운영체제·요청 사유를 확인합니다.</li><li><b>3.</b> <b>제거 승인</b> → 해당 장비에서 제거 진행, 완료 시 장비 인증 키 폐기·관리 대상 해제. <b>제거 거부</b> → 차단, 에이전트는 계속 동작.</li></ol></div><div className="rounded-xl border border-slate-300 bg-white p-6"><b>홈페이지 제거 요청 → 토큰 발급</b><ol className="mt-3 space-y-2 text-slate-700"><li><b>1.</b> 고객사가 홈페이지 ‘에이전트 제거 요청’ 양식을 보내면 회사 메일로 접수됩니다.</li><li><b>2.</b> 장비·계약 상태를 확인한 뒤 장비·사용자 → 대상 장비의 <b>‘제거 토큰 발급’</b>을 누릅니다.</li><li><b>3.</b> 표시된 제거 토큰·실행 명령을 전용 제거 도구와 함께 회신 이메일로 전달합니다. 고객사는 승인 대기 없이 바로 제거합니다. (토큰 2시간 유효)</li></ol></div></div><Box title="주의" warn>관리 서버에 연결할 수 없으면 제거가 차단됩니다. 승인·토큰 발급은 관리자·보안담당자만 가능하며 결정 이력은 감사 기록에 남습니다. 제거 도구는 홈페이지에서 직접 제공하지 않습니다.</Box></section>
<section><Title n="5">Shadow AI 사건 처리</Title><ol className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6"><li>사건을 펼쳐 발생 위치·현재 조치·처리 방법을 확인합니다.</li><li>업무용이면 ‘해당 Client 승인 설정 보기’에서 승인합니다.</li><li>비업무용이면 ‘차단 관리 열기’에서 차단을 유지·추가합니다.</li><li>사용자 안내와 조치가 끝난 뒤 ‘확인 후 해결 처리’를 누릅니다.</li></ol></section>
<section><Title n="6">보안 알림</Title><div className="mt-5 grid gap-4 md:grid-cols-3"><Box title="High">API 키·개인키·대량 고객정보 유출 등 즉시 대응</Box><Box title="Med">정책 위반 가능성을 담당자가 검토</Box><Box title="Low">운영 참고와 추세 확인</Box></div><p className="mt-4 text-slate-600">삭제는 화면에서 숨기며 감사 기록은 남습니다. 여러 건은 필터 후 전체 선택으로 처리합니다.</p></section>
<section><Title n="7">차단과 카탈로그</Title><ul className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6"><li>에이전트 제어 → 차단 관리에서 PC·사용자·AI 단위 정책을 설정합니다.</li><li>없는 AI는 프로세스명과 도메인을 사용자 정의 AI로 등록합니다.</li><li>AI 목록 관리의 신규 후보는 검토 후 승인·배포합니다.</li><li>사라진 서비스는 ‘서비스 종료’로 바꿔 감사 기록을 보존합니다.</li></ul></section>
<section><Title n="8">100대 이상 운영</Title><Box title="대규모 Client">25대 이상이면 밀집 표로 자동 전환됩니다. 검색, 온라인/오프라인 필터, 25·50·100개 페이지 크기를 사용하고 미승인·오프라인 대상을 우선 확인하십시오.</Box></section>
<section><Title n="9">라이선스</Title><Box title="15일 무료" warn>최초 서버 설치일부터 15일간 무료입니다. 만료 후 서버가 Agent 정책 조회·로그 수집·탐지·차단 요청을 거부해 기능이 자동 중지됩니다. Agent와 기존 로그는 유지되며 구독 키 인증 후 재개됩니다.</Box></section>
<section><Title n="10">권한과 감사</Title><ul className="mt-5 space-y-3 rounded-xl border border-slate-300 bg-white p-6"><li>관리자·보안담당자만 승인·차단·삭제를 수행합니다.</li><li>감사자·열람자는 상태만 확인합니다.</li><li>원문 대신 위반 유형·위험도·시각·해시·마스킹 증거를 기본 저장합니다.</li><li>원문 열람과 관리자 작업은 감사 기록을 남깁니다.</li></ul></section>
<section><Title n="11">장애 대응</Title><div className="mt-5 overflow-hidden rounded-xl border border-slate-300 bg-white"><table className="w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-3">증상</th><th className="p-3">조치</th></tr></thead><tbody className="divide-y divide-slate-200"><tr><td className="p-3 font-bold">Client 미표시</td><td className="p-3">Agent 상태 → 서버 주소 → TCP 3100 → 오류 로그 확인</td></tr><tr><td className="p-3 font-bold">승인 후 차단</td><td className="p-3">온라인 여부, 라이선스, 정책 수신 시각, AI 식별자 확인</td></tr><tr><td className="p-3 font-bold">지원 요청</td><td className="p-3">시각, Client, 사용자, 이벤트 코드와 설치·Agent·제거 로그 전달</td></tr></tbody></table></div></section>
<div className="flex gap-3"><a href="/downloads/einsguard-ai" className="rounded-xl bg-slate-950 px-6 py-4 font-black text-white">자료실</a><a href="/docs/einsguard-ai/install" className="rounded-xl border border-slate-300 bg-white px-6 py-4 font-black">설치 매뉴얼</a></div>
</article></main><Footer/></>}
