import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Badge from "@/components/ds/Badge";
import { createPageMetadata } from "@/lib/seo";

export const metadata=createPageMetadata({path:"/downloads/einsguard-ai",title:"EINSGUARD AI 0.3.0 다운로드 | EINSTECH",description:"15일 Trial 관리 서버와 Windows·Linux·macOS Agent 1.3.1 및 SHA-256 체크섬을 제공합니다."});
const packages=[
 {title:"AI GUARD 관리 서버",platform:"LINUX SERVER · 0.3.0-TRIAL",file:"einsguard-ai-0.3.0-trial-linux.tar.gz",sha:"acf49eafb7b25244ea538724adbee2ce111476f7ce96ed0f09c68362f98b45f5",items:["Linux x86_64·arm64","Ollama·OpenAI 호환 내부 LLM","Windows·Linux·macOS Agent 포함","15일 무료 · 관리 대상 5대"]},
 {title:"Windows Agent",platform:"WINDOWS CLIENT · 1.3.1",file:"EINSGUARD-AI-Windows-Agent-1.3.1.exe",sha:"2bfdbd3b534f849a3a17cadb98d195f9c661d896d11fbcf4f54f45b7749b9185",items:["서버 주소만 입력 · 승인 등록","클립보드·CLI·CLI 첨부 파일 DLP","Claude·Codex 실행 정책","장비 전용 키 자동 수령"]},
 {title:"Linux Agent",platform:"LINUX CLIENT · 1.3.1",file:"einsguard-ai-agent-1.3.1-linux.tar.gz",sha:"280e6241bd1076f0553394db2960c4e2d96bf6110b65843bbadac5f068dc37d0",items:["서버 주소만 입력 · 승인 등록","CLI 첨부 텍스트 파일 검사","로컬 사용자 추가·삭제 추적","현재 API·키 상태 확인"]},
 {title:"macOS Agent",platform:"MACOS CLIENT · 1.3.1",file:"einsguard-ai-agent-1.3.1-macos.tar.gz",sha:"87a262c16959113f2c1636aae73f5449639fdc245e2c371f14aa5272b3b4bc42",items:["macOS 13 이상","서버 주소만 입력 · 승인 등록","CLI 첨부 텍스트 파일 검사","현재 API·키 상태 확인"]},
 {title:"Windows 제거 도구",platform:"WINDOWS CLEANUP · 1.3.1",file:"EINSGUARD-AI-Windows-Cleanup-1.3.1.exe",sha:"665e2d0623062fd0ece28bfc01ebd7fbb28eea15bc0477dd890ad7b139f724d9",items:["예약 작업 정리","정책 백업 복원","PATH 복원","제거 로그 보존"]},
];
export default function DownloadPage(){return <><Header/><main className="bg-slate-50 pt-16 text-slate-900"><section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-page px-6 lg:px-12"><Badge color="acid">DOWNLOAD CENTER</Badge><h1 className="mt-6 font-display text-5xl font-black">EINSGUARD AI 0.3.0-trial</h1><p className="mt-5 max-w-3xl text-base leading-8 text-white/70">고객사 내부 LLM 환경을 선택할 수 있는 온프레미스 공개 후보 버전입니다. 운영 서버가 아닌 별도 시험 환경에서 먼저 검증하십시오.</p></div></section><section className="py-16"><div className="mx-auto max-w-page px-6 lg:px-12"><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{packages.map(p=><article key={p.file} className="flex flex-col rounded-[24px] border border-slate-300 bg-white p-7 shadow-sm"><div className="font-mono text-[11px] font-black tracking-widest text-blue-700">{p.platform}</div><h2 className="mt-3 font-display text-2xl font-black">{p.title}</h2><ul className="mt-5 flex-1 space-y-2 text-sm text-slate-600">{p.items.map(x=><li key={x}>✓ {x}</li>)}</ul><a download href={`/downloads/${p.file}`} className="mt-7 rounded-xl bg-slate-950 px-5 py-4 text-center text-sm font-black text-white">설치 파일 다운로드</a><a download href={`/downloads/${p.file}.sha256`} className="mt-2 rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-bold">SHA-256 파일</a><code className="mt-4 break-all rounded-lg bg-slate-100 p-3 text-[10px] leading-5 text-slate-700">{p.sha}</code></article>)}</div><div className="mt-10 grid gap-5 lg:grid-cols-3"><a href="/docs/einsguard-ai/admin" className="rounded-[20px] bg-slate-800 p-7 text-white"><div className="text-xs font-bold text-slate-300">ADMIN OPERATIONS</div><div className="mt-2 text-2xl font-black">관리자 운영 매뉴얼 →</div></a><a href="/docs/einsguard-ai/install" className="rounded-[20px] bg-blue-800 p-7 text-white"><div className="text-xs font-bold text-blue-200">WINDOWS · LINUX · MACOS</div><div className="mt-2 text-2xl font-black">설치·설정 매뉴얼 →</div></a><div className="rounded-[20px] border border-amber-400 bg-amber-50 p-7"><div className="font-black">원문 기본 미저장</div><p className="mt-2 text-sm leading-6 text-slate-700">내용은 내부 LLM 판정 중에만 일시 사용하며 기본 정책에서는 데이터베이스에 저장하지 않습니다.</p></div></div></div></section></main><Footer/></>}
