import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import Badge from "@/components/ds/Badge";
import { createPageMetadata } from "@/lib/seo";

export const metadata=createPageMetadata({path:"/downloads/einsguard-ai",title:"EINSGUARD AI 1.0 다운로드 | EINSTECH",description:"EINSGUARD AI 1.0 관리 서버와 Linux·macOS Agent, 설치 매뉴얼 및 SHA-256 체크섬을 제공합니다."});

const packages=[
  {title:"AI GUARD 관리 서버",platform:"LINUX SERVER · 1.0.0",file:"einsguard-ai-server-1.0.0-linux.tar.gz",sha:"1701429ef11073db56c7630948cd4fbce27be468ae2ed394a6a8f4cec501650d",items:["Linux x86_64·arm64","Docker/Podman Compose","대시보드·DB·로그 수집기","15일 시험 라이선스 지원"]},
  {title:"Linux Agent",platform:"LINUX CLIENT · 1.0.0",file:"einsguard-ai-agent-1.0.0-linux.tar.gz",sha:"bfe73576395e00d43193543683a7be5c7c194c6acbc91c1cc759101359a13dc0",items:["systemd 자동 실행","앱·CLI·브라우저 AI 감지","승인·차단 정책 적용","상태·삭제·로그 도구 포함"]},
  {title:"macOS Agent",platform:"MACOS CLIENT · 1.0.0",file:"einsguard-ai-agent-1.0.0-macos.tar.gz",sha:"f84ec57fe07efa87dc3edbf797b221602269365b26596bffcbed304d81d07f28",items:["macOS 13 이상","launchd 자동 실행","앱·CLI·브라우저 AI 감지","상태·삭제·로그 도구 포함"]},
];

export default function DownloadPage(){return <><Header/><main className="bg-slate-50 pt-16 text-slate-900"><section className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-page px-6 lg:px-12"><Badge color="acid">DOWNLOAD CENTER</Badge><h1 className="mt-6 font-display text-5xl font-black">EINSGUARD AI 1.0</h1><p className="mt-5 max-w-3xl text-base leading-8 text-white/70">관리 서버와 운영체제별 Agent를 각각 다운로드할 수 있습니다. 고객 시험망에 관리 서버를 먼저 설치한 뒤 Agent를 연결하십시오.</p></div></section><section className="py-16"><div className="mx-auto max-w-page px-6 lg:px-12"><div className="grid gap-6 lg:grid-cols-3">{packages.map(p=><article key={p.file} className="flex flex-col rounded-[24px] border border-slate-300 bg-white p-7 shadow-sm"><div className="font-mono text-[11px] font-black tracking-widest text-blue-700">{p.platform}</div><h2 className="mt-3 font-display text-2xl font-black">{p.title}</h2><ul className="mt-5 flex-1 space-y-2 text-sm text-slate-600">{p.items.map(x=><li key={x}>✓ {x}</li>)}</ul><a download href={`/downloads/${p.file}`} className="mt-7 rounded-xl bg-slate-950 px-5 py-4 text-center text-sm font-black text-white">패키지 다운로드</a><a download href={`/downloads/${p.file}.sha256`} className="mt-2 rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-bold">SHA-256 파일</a><code className="mt-4 break-all rounded-lg bg-slate-100 p-3 text-[10px] leading-5 text-slate-700">{p.sha}</code></article>)}</div><div className="mt-10 grid gap-5 lg:grid-cols-2"><a href="/docs/einsguard-ai/install" className="rounded-[20px] bg-blue-800 p-7 text-white"><div className="text-xs font-bold text-blue-200">INSTALL & OPERATION GUIDE</div><div className="mt-2 text-2xl font-black">설치·사용·제거 매뉴얼 →</div></a><div className="rounded-[20px] border border-amber-300 bg-amber-50 p-7"><div className="font-black">시험 전 확인</div><p className="mt-2 text-sm leading-6 text-slate-700">관리 서버 주소와 고객별 Agent 키가 필요합니다. Agent 키는 공개하거나 다른 고객사와 공유하면 안 됩니다. 운영망 적용 전 별도 시험 PC에서 검증하십시오.</p></div></div></div></section></main><Footer/></>}
